### ISSUE TITLE
Tancament versio 2.0.1

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/rolsac2#10]

**Comment by slromero-indra** [comment]
Hemos comiteado los scripts para generar las tablas de bbdd. 

Para arrancar, debéis configurar en el standalone.xml de jboss tanto el datasource como especificar la ruta de propiedades (en el código fuente, los ficheros están en \rolsac2\scripts\configuracio). Ejemplo de como configurarlo en el standalone.xml: 

```
<system-properties>
        <property name="es.caib.rolsac2.properties" value="/app/properties/rolsac2.properties"/>
        <property name="es.caib.rolsac2.system.properties" value="/app/properties/rolsac2.system.properties"/>
</system-properties>


<datasource jndi-name="java:jboss/datasources/rolsac2DS" pool-name="rolsac2DS">
                    <connection-url>jdbc:oracle:thin:@url:1521:xxxx</connection-url>
                    <driver>oracle</driver>
                    <new-connection-sql>BEGIN EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = rolsac2'; END;</new-connection-sql>
                    <security>
                        <user-name>www_rolsac2</user-name>
                        <password>pwd</password>
                    </security>
                </datasource>
```

Para generar la versión , sólo hace falta coger el tag rolsac2-2.0-S1_1

**Comment by bgarcia-dgtic** [comment]
Hola,
He descarregat el projecte i a l'hora d'empaquetar em dóna errors. Uns evío correu amb els errors.

**Comment by bgarcia-dgtic** [comment]
hola,
He executat l'escript de BBDD 01_create_shecma.sql i em dóna error. El motiu és el table space.
Serveis Web ha creat els següents tables space:

1. ROLSAC2_DADES 
2. ROLSAC2_INDEX 
3. ROLSAC2_LOB

Podeu actualitzar els scripts de BBDD perquè utilitzin aquests table space?

**Comment by slromero-indra** [comment]
Hemos actualizado los scripts para quitar toda referencia a tablespace en la creación de tablas que es más recomendable.

Es importante que exista el usuario www_rolsac2 ya que se le da permisos sobre las tablas y se le crea los sinónimos (en caso de que el usuario de la aplicación jboss fuese otro, habría que renombrar por el usuario correspondiente).

**Comment by bgarcia-dgtic** [comment]
L'script drop schema.sql no elimina totes les taules. Només elmina una part.

**Comment by bgarcia-dgtic** [comment]
Bon dia,
Hem conseguit desplegar l'aplicació però fent els següents canvis.

1. Fitxer /rolsac2-persistence/src/main/resources/META-INF/persistence.xml

   Canviar l'etiqueta `<jta-data-source>java:jboss/datasources/rolsac2DS</jta-data-source>` per `<jta-data-source>java:/es.caib.rolsac2.db</jta-data-source>`

2. Fitxer /rolsac2-ejb/src/main/resources/META-INF/jboss-ejb3.xml

    Comentar l'etiqueta `<assembly-descriptor>` sencera.
    `<assembly-descriptor>`
                 `<s:security>`
                     `<ejb-name>*</ejb-name>`
                     `<s:security-domain>seycon</s:security-domain>`
                 `</s:security>`
  `</assembly-descriptor>`

3. Fitxer /rolsac2-back/src/main/webapp/WEB-INF/jboss-web.xml
    Comentar l'etiqueta `<security-domain>seycon</security-domain>`

A JBoss 7 utilitzarem Keycloak en lloc de seycon.
