### ISSUE TITLE
Missatge d'error quan no es té ROL

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#100]
En fer la migració de BD, amb l'script de càrrega inicial, ens hem adonat que no hi ha un missatge d'error específic quan un usuari entra i no té el rol associat.

Podeu controlar-ho?

(ens apareix un error de PerfilException.xhtml.xhtml)

**Comment by slromero-indra** [comment]
Se solucionó en el último commit https://github.com/GovernIB/rolsac2/commit/293a4d090aab83dd9e019ecd606cc88740cc61c2 , cuando podáis lo validáis. Ahora mismo cuando entras a una ventana que no puedes por perfil manda al siguiente error:

![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/02188694-66b8-4cee-9bda-c54372dde048)

**Comment by scalafat-dgtic** [comment]
No sé si es controlable pero estando en el rol Gestor, me he borrado el rol, he cerrado sesión y he vuelto a iniciar sesión en pestaña de incógnito (de cero). Al hacerlo, me ha entrado con el rol Gestor, aunque se ve en el desplegable que no podría.

![image](https://github.com/GovernIB/rolsac2/assets/44995350/f34ca36e-db73-4706-a81b-3cc85c1a997a)

**Comment by slromero-indra** [comment]
Subido los cambios, cuando podáis lo validáis.

**Comment by slromero-indra** [comment]
Hemos realizado varios cambio debido a que el error puede deberse porque haya cogido un rol incorrecto como RS2_API o bien que en los datos de sesión almacenados no se había almacenado la entidad.

Si os sigue dando problemas, nos comentáis porque deberemos borrar el dato de sessión asociado al usuario (al ser de una versión anterior, se ha creado un dato inconsistente).

Con los nuevos cambios, ya no se producen los errores citados anteriormente.

**Comment by scalafat-dgtic** [comment]
Al entrar en el rol de Gestor (previamente se había borrado y se ha vuelto a crear como parte de las pruebas hechas) ahora da un NullPointer.

Imaginamos que está relacionado con lo que nos habéis comentado. ¿Qué tenemos que borrar en BD para poder acceder bien? 
Curiosamente, tras haber saltado el NullPointer, si volvemos a entrar en pestaña de incógnito, sí que podemos entrar bien en el rol.

![Image](https://github.com/user-attachments/assets/4af2d59e-03e7-4ba6-846c-7c89c4cab7f1)


_2024-10-02 11:20:08,102 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-49) null: java.lang.NullPointerException
	at java.base/java.lang.Long.compareTo(Long.java:1587)
	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.SessionBean.lambda$actualizarUnidadAdministrativa$0(SessionBean.java:574)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)_
