### ISSUE TITLE
AdmContenido - Cambiar árbol orgánico

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#107]
Replicar árbol de roles de Gestor e Informador en AdmContenido

![image](https://github.com/GovernIB/rolsac2/assets/44995350/f6389296-dd4a-4c64-92de-ff9ed2b358b3)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/99dccf4f-e20c-404d-9a4b-e141d37bb710)

**Comment by slromero-indra** [comment]
Incorporado el árbol en adm contenido en el tag [ rolsac-2.0-S19_1 ](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S19_1), cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
Parece que al entrar por primera vez en Administrador de Contenido el botón no muestra el nombre de la UA. 

![image](https://github.com/GovernIB/rolsac2/assets/44995350/b1133965-229f-461d-990d-54bbf9639064)

Si entramos en el rol Gestor y volvemos al Administrador de Contenido ya se muestra bien

![image](https://github.com/GovernIB/rolsac2/assets/44995350/452e3011-d9a0-4463-849d-35ce73a96672)

**Comment by slromero-indra** [comment]
Cambios incorporados en el tag  [rolsac-2.0-S20_1](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S20_1), cuando podáis lo validáis.
