### ISSUE TITLE
Adm Entitat - Revisar pantalla Organigrama DIR3

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#109]
Com es va comentar per correu, es demana:

- Revisar comportament idiomàtic quan es mostra el resultat de la sincronització amb DIR3 (columna dreta) i filtratge dels resultats per idioma a l'organigrama que té ROLSAC2 (columna esquerra)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/ecaac319-1c95-44a6-b1c1-e7db2a3690fe)

- Revisar comportament quan s'entra dins la pantalla de l'organigrama, ja que tarda en carregar i no sabem si és que s'executa el refresc de l'organigrama. Només s'hauria de refrescar quan es prem el botó de 'Refrescar organigrama DIR3' no cada vegada que s'entra.

**Comment by scalafat-dgtic** [comment]
Revisar el idioma en el que se descarga la información del organigrama DIR3 (en la captura anterior se ve que estamos en catalán y recibimos la información en castellano)

**Comment by slromero-indra** [comment]
Ahora según el idioma de sesión, se muestra en castellano o catalán. Los cambios están en el tag  [ rolsac-2.0-S19_1 ](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S19_1), cuando podáis lo validáis.
