### ISSUE TITLE
Adm Contingut - Procediments - No es veuen els temes al mòdul de temàtica

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#115]
Amb la inserció dels nous canvis de BD, en seleccionar un tema dels disponibles, no es veuen els temes seleccionats en el mòdul

![image](https://github.com/GovernIB/rolsac2/assets/44995350/a0ddf463-deb7-4a14-9e38-617402d7011d)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/90831d92-538d-4a24-8540-13da88b3e8f1)

**Comment by bgarcia-dgtic** [comment]
Ha funcicionat correctament.
