### ISSUE TITLE
S14-2 IMPLEMENTACIÓN PLUGIN ROLSAC2 PARA SISTRA2

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#117]
- Conexión con el nuevo api
- Análisis de cómo adaptar las peticiones antiguas a las nuevas
- Implementación de la lógica interna

**Comment by scalafat-dgtic** [comment]
Según correo, ha habido errores en sistramit de SISTRA2, queda pendiente

**Comment by jparedes-indra** [comment]
Para configurar esta nueva conexión debe modificarse el plugin de catálogo procedimiento de SISTRA2:

En cada entorno deberán adaptarse ciertas propiedades, como las urls. 

![imagen](https://github.com/GovernIB/rolsac2/assets/67064375/5036d7e1-fb07-4e8e-a8c2-95bdb557b540)
