### ISSUE TITLE
S15-3 – MEJORAS SOBRE EL PLUGIN CATALOGO PROCEDIMIENTO SISTRA2 Y EL API REST ROLSAC2

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#122]
- Mejorar el api para evitar consultas innecesarias al consultar procedimientos y servicios y obtener datos LOPD.
- Solventar errores al usar el plugin desde el frontal de SISTRA2

**Comment by slromero-indra** [comment]
Buenas, hemos subido una nueva versión (tag [rolsac-2.0-S14_2](https://github.com/governIB/rolsac2/tree/rolsac-2.0-S14_2)) que se encarga de mejorar el restapi.

Hemos actualizado la información que se almacena de la lopd a nivel de entidad, ahora se guarda tanto la cabecera como el enlace de la plantilla lopd (se ha introducido cierta información básica ya que no disponemos de la información en producción).

Si no queréis volver a recrear toda la base de datos, es ejecutar las siguientes instrucciones:
```
ALTER TABLE "RS2_TRAENT" ADD "TREN_LOPDCB"  VARCHAR2(4000 CHAR) NULL;
ALTER TABLE "RS2_TRAENT" ADD "TREN_LOPDPL"  VARCHAR2(4000 CHAR) NULL;
```

Respecto a las traducciones, se pueden introducir a mano desde el menú LOPD de un admin. entidad o bien podéis ejecutar las siguientes sql:

```
truncate table RS2_TRAENT;
    
Insert into RS2_TRAENT (TREN_CODIGO,TREN_CODENT,TREN_IDIOMA,TREN_DESCRI, TREN_LOPDFI, TREN_LOPDDS, TREN_LOPDDR, TREN_LOPDCB, TREN_LOPDPL, TREN_UACOMU) values (RS2_TRAENT_SEQ.NEXTVAL,1,'ca','GOIB descenti ca','Tramitació del procediment','El destinatari de la lopd','El dret de la lopd', 'De conformitat amb el reglament (UE) 2016/679 i la legistació vigente en matèria de protecció de dades, s''informa del tractament de les dades personales que contè aquest tràmit', 'http://www.caib.es/plantillaCAT.pdf' ,'Responsable lopd comú');
Insert into RS2_TRAENT (TREN_CODIGO,TREN_CODENT,TREN_IDIOMA,TREN_DESCRI, TREN_LOPDFI, TREN_LOPDDS, TREN_LOPDDR, TREN_LOPDCB, TREN_LOPDPL, TREN_UACOMU) values (RS2_TRAENT_SEQ.NEXTVAL,1,'es','GOIB descenti es','Tramitación del procedimiento','El destinatario de la lopd','El derecho de la lopd','De conformidad con el reglamento (UE) 2016/679 y la legistación vigente en materia de protección de datos, se informa del tratamiento de los datos personales que contiene este trámite', 'http://www.caib.es/plantillaCAT.pdf' ,'Responsable lopd común');

commit;

```
