### ISSUE TITLE
OAE - Revisar tamaño fuentes

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#123]
Se pide aumentar el tamaño de las fuentes, en general, tanto de etiquetas de tablas, campos, etc. como de los contenidos en un 125% (font-size: 1.2em?)

**Comment by slromero-indra** [comment]
Actualizaremos el tamaño de la fuente a una mayor (1.2 em de momento para probar).

Hay que tener en cuenta que aumentar el tamaño produce que algunos iconos en los botones se vean entrecortados o tablas que tienen alguna columna con un ancho fijo, se queden totalmente descuadradas (por lo que hay que revisar más estilos que simplemente aumentar el tamaño a 1.2em).

Os pasamos una captura tras varios análisis, donde se ve que algunas imágenes se descuadran (por ejemplo, el botón de seleccionar UA y las flechas de la paginación), pero os podéis hacer una idea de la visualización global cuando se aplique el estilo 1.2em:
![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/d3b80105-d97e-496b-9830-10c0c3770350)

**Comment by scalafat-dgtic** [comment]
Hola Sergio, no hay problema si otros aspectos se ven afectados. Con que se corrijan en consecuencia (p.ej: aumentando el tamaño del botón e incluso manteniendo su tamaño inicialmente propuesto si es necesario), ya nos basta. 
El problema principal es que el texto de las tablas y modales se ve pequeño, a ojos de la OAE, y es lo que se pide. Si hay algún aspecto que presenta dificultades, lo miramos y tratamos de adaptarlo.

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización, ¿lo podéis revisar?

**Comment by scalafat-dgtic** [comment]
Desde la OAE se nos solicita la revisión del tamaño también de las etiquetas de manera proporcional al resto de fuentes.

![image](https://github.com/GovernIB/rolsac2/assets/44995350/f72ca0d0-8bf7-4e7d-8128-edc85be6e1b8)

**Comment by slromero-indra** [comment]
Se ha actualizado la fuente de la aplicación en todos los labels. Dicho cambio afecta a toda la aplicación de la siguiente manera:
 - En algunos labels, en vez de utilizar la etiqueta de primefaces outputText, se utiliza la etiqueta estandard h:outputLabel. Se ha actualizado a primefaces para poder aplicarle estilos correctamente.
 - Se ha cambiado el tamaño de los dialogs para que cupiera correctamente sin scroll (de todos los perfiles y ventanas).
 - En el caso del dialog de procedimientos y servicios, se ha tenido que revisar cada uno de las secciones para ajustarlo al tamaño de los labels y cambiar algún margen para solucionar algún problema visual. 

 Está comiteado en el tag [S21_1 ](https://github.com/GovernIB/rolsac2/commits/rolsac-2.0-S21_1/), cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
El tamaño de las etiquetas está OK aunque puede que falte ajustar en los siguientes:

- Con "Taxa"
![image](https://github.com/GovernIB/rolsac2/assets/44995350/3460ba41-6d6c-4f0d-ab54-516e400d05a1)

- Campo "correo electrónico"
![image](https://github.com/GovernIB/rolsac2/assets/44995350/bed35ed3-11e6-4334-bfee-9bd3ae6e7b99)

Además, y esto es importante, aunque no sé si está relacionado con la redimensión de los tamaños de las etiquetas pero ahora no se pueden seleccionar para editar o consultar las opciones de los módulos de la derecha:

![image](https://github.com/GovernIB/rolsac2/assets/44995350/263c309f-ed06-4d90-8a65-0b34bdb6a479)

**Comment by slromero-indra** [comment]
En el tag [rolsac-2.0-S21_2](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S21_2) hemos incorporado los cambios:
 - Ajustado los espacios.
 - Los módulos laterales ya pueden seleccionarse.
Cuando podáis lo validáis.
