### ISSUE TITLE
OAE - Idioma por defecto

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#124]
Se pide que el gestor de contenido esté solo en catalán, por tanto, habría que quitar en la configuración de idioma, que se pudiera cambiar. (por ahora, que se oculte el desplegable)

Cuando la opción por defecto del navegador sea en castellano, que siga mostrándose en catalán

![image](https://github.com/GovernIB/rolsac2/assets/44995350/c79458ea-64a1-4481-9e40-16a5c5edf739)

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización, ¿lo podéis revisar?
hemos añadido una propiedad a nivel de configuracion de entidad para poder modificar el idioma de los gestores

**Comment by scalafat-dgtic** [comment]
Veim que vàrem demanar només pel perfil de gestor de contingut (però no sé perquè me vaig limitar a aquest perfil). Ho podem ampliar a l'Administrador de Contingut i a l'Informador? Disculpau el canvi.

Per altra costat, veim que les etiquetes de la configuració en els dos idiomes no coincideix:
![image](https://github.com/GovernIB/rolsac2/assets/44995350/3275cd17-9a5d-402e-b0a6-3c832132d038)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/c89d9efe-1880-4704-8a5a-ca787775844d)

**Comment by slromero-indra** [comment]
Se han subido los cambios en el tag rolsac-2.0-S18_1, podéis revisarlo?

**Comment by scalafat-dgtic** [comment]
Falta correspondencia entre la opción subrayada en catalán y castellano. 

CATALÀ
![image](https://github.com/GovernIB/rolsac2/assets/44995350/18bdfda7-0a85-4146-b782-3497535951b5)

CASTELLANO
![image](https://github.com/GovernIB/rolsac2/assets/44995350/38c0a14a-78d8-4d92-944c-e04828b238f1)

**Comment by slromero-indra** [comment]
Hemos generado un tag nuevo [rolsac-2.0-S18_2 ](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S18_2) que soluciona el problema con los literales.
