### ISSUE TITLE
OAE - Primera opción de pestaña idioma

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#125]
En los modales, que la primera opción de idioma esté siempre el catalán. 
![image](https://github.com/GovernIB/rolsac2/assets/44995350/1ac7a2a2-dba1-46c4-b20c-b2428d7b0b5e)

(en la imagen aparece, pero a la OAE no)

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización, ¿lo podéis revisar?
hemos añadido una propiedad a nivel de configuracion de entidad para poder modificar el idioma principal a mostrar en los dialogs
