### ISSUE TITLE
OAE - Implementación Avisos y alertas

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#127]
Se pide priorizar la implementación del módulo de "Avisos y alertas" desde el Administrador de Entidad

![image](https://github.com/GovernIB/rolsac2/assets/44995350/5df37df0-0a43-464f-bb6a-3ab061d26103)

**Comment by scalafat-dgtic** [comment]
1. Al querer insertar una alerta en una Unidad Administrativa no aparece el menú de Unidad Administrativa hasta que no se le da al botón de Guardar (momento en qué aparece porque es un campo obligatorio). También aparece el desplegable de Perfil pero no sé si se trata de un error (debería esconderse?).

![image](https://github.com/GovernIB/rolsac2/assets/44995350/142a04a3-bc24-49d7-8f14-d8676aaf8e02)

Tras darle a 'Desar'
![image](https://github.com/GovernIB/rolsac2/assets/44995350/d2496be4-e32f-419f-81c1-5339f4556e5f)

2. Como se ve en las imágenes, se corta el check (el texto) de 'incluir descendentes', es posible ponerlo en la línea siguiente?
3. No sé si puede hacer algo, pero al insertar alertas, y refrescar, se pierde la sesión y se devuelve un .xhtml

![image](https://github.com/GovernIB/rolsac2/assets/44995350/f33a84bf-a330-497d-8a94-49759fd16c44)


2024-02-13 14:05:54,354 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-1) viewId:/monitorizacion/viewConfiguracionesAlertas.xhtml - No se pudo restablecer la vista /monitorizacion/viewConfiguracionesAlertas.xhtml.: javax.faces.application.ViewExpiredException: viewId:/monitorizacion/viewConfiguracionesAlertas.xhtml - No se pudo restablecer la vista /monitorizacion/viewConfiguracionesAlertas.xhtml.
	at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:218)

4. Hemos hecho pruebas con alertas en distintos perfiles, pero aparecen en todos ellos

![image](https://github.com/GovernIB/rolsac2/assets/44995350/53680269-0ea5-470c-b788-e70f3b5b5dcf)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/856cbedd-43ba-4886-996e-25538a5da044)

5. No vemos las alertas en Unidades Administrativas (tenemos un aviso en la Consejería Hacienda y no lo vemos)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/6a649e92-525e-4444-a753-664995a81832)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/c41e653a-6279-4a7c-9d8f-663c627cc096)

6. ¿Sobra una columna? 

![image](https://github.com/GovernIB/rolsac2/assets/44995350/6fdeb22d-c66e-4c17-bac6-6551970b2c7e)

7. ¿Tal vez podríamos destacar las alertas con un fondo de color distinto? (se admiten propuestas, en la imagen hemos colocado una prueba de 'antiquewhite')

![image](https://github.com/GovernIB/rolsac2/assets/44995350/5f98fe61-7bc9-4c89-941a-aa95c25c3b1a)

**Comment by scalafat-dgtic** [comment]
OK al 1, 2 y 6
Sobre el punto 4, vemos bien el desarrollo actual, gracias. 

Aprovecho para apuntar si se puede establecer, en la pantalla de avisos y alertas:
- la ordenación de las mismas por fecha de inicio decreciente (de más reciente a más antigua) 

![image](https://github.com/GovernIB/rolsac2/assets/44995350/99c1aa8c-0e2f-47b8-a9b6-fd4714ecde9e)

**Comment by slromero-indra** [comment]
Generado un nuevo tag [ rolsac-2.0-S19_1 ](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S19_1), que incorpora el reordenación descendiente por fecha de inicio y también incorporado un nuevo estilo en las alertas (hemos revisado lo del error que comentáis que se produce cuando se crea y refresca pero no ha sido posible). Cuando podáis lo validáis.

Faltaría revisar el error que comentáis con las UAs.

**Comment by slromero-indra** [comment]
Los cambios de la gestión de alertas de tipo unidad administrativa están en el tag  [rolsac-2.0-S20_1](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S20_1), cuando podáis lo validáis.

**Comment by slromero-indra** [comment]
Actualmente para calcular que alertas de tipo unidad administrativa están pendientes de leer, se obtiene las unidades administrativas asociadas al usuario. Posteriormente, a partir de las unidades anteriores, se obtiene también los padres inmediatos teniendo una lista que está conformado por las UAs asociadas al usuario y los respectivos padres. Con dicha lista, se calcula las alertas/avisos asociadas a alguna unidad administrativa que esté dentro de esa lista.

Entendemos que hay 2 enfoques, o bien los padres (como funciona actualmente) o bien los hijos. Entendemos que tiene más lógica que, por el tipo de información que debería de almacenar un alerta y su alcance, debería ser la unidad administrativa y sus padres directos.  


**Ejemplo de una estructura de UAs (con una alerta a nivel de dirección de gabinete)**
![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/c8db7e94-2c13-4b51-bc89-58066a5ace07)

**Funcionamiento enfoque sólo padres (FUNCIONAMIENTO ACTUAL)**
En este caso, los usuarios 2 y 4 son los usuarios que verían una alerta a nivel de Dirección de gabinete (debido a que, por ejemplo, el usuario 2 tiene de padre a Dirección Gabinete). 
 
![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/eb50eb07-1ad9-4296-9b87-ec278917b3dd)



**Funcionamiento enfoque sólo hijos**
En este caso, el usuario 1 sería el único que lo vería (esto trae consecuencias ya que un usuario que tuviese asociado el usuario GOIB, vería todas las alertas).
 
![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/bb0ce9ba-2bc6-43af-a0b1-cec7c2eba41c)

**Comment by scalafat-dgtic** [comment]
OK al funcionamiento actual. Vemos más lógico que las alertas las vean aquellos que se encuentran en la misma UA o en las UAs hijas de aquella que tiene activada la alerta.
