### ISSUE TITLE
OAE - Poder exportar en CSV los resultados de búsqueda

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#128]
Para no perder funcionalidades respecto a ROLSAC1, se pide que al realizar búsquedas de cualquier tipo (procedimientos, normativas, servicios, etc) se puedan exportar resultados en un fichero .csv.

Como mejora de esta issue, se propone poder seleccionar qué columnas se quiere que aparezcan en el fichero exportado.

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización, ¿lo podéis revisar?

**Comment by scalafat-dgtic** [comment]
Ja heu esmentat al document de planificació enviat fa uns dies que es faran millores, però us escric algun dels errors detectats:

- A CSV, l'exportació no admet camps amb més d'un valor (p.ex: la columna de "públic objectiu" hauria de Ciutadà i Empreses i es resol afegint-ho a la columna següent, el que desquadra el resultat final)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/a447ca3a-66d0-4425-aa25-44492f45eb1f)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/22dccae3-3e49-4e04-9ac2-e407eaefff15)

- A CSV (als altres va bé), a un procediment, l'objecte passa a la següent columna (no sé el motiu)
 
![image](https://github.com/GovernIB/rolsac2/assets/44995350/eda77394-3d63-4786-9791-47927fb24746)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/74b67ba7-d2c5-46d4-8db1-ff400465c964)

- Canviar el nom del fitxer exportat per "Llistat<Tipus>_<data en format AAAAMMDD>", per exemple: LlistatProcediments_20231215.

- La finestra té doble 'scroll' però el corresponent al modal no és necessari

![image](https://github.com/GovernIB/rolsac2/assets/44995350/e6be0b19-8760-43df-8ef1-97fba70cb44e)

**Comment by slromero-indra** [comment]
Hemos incluido todas las mejoras en el tag 17_1, por favor, cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
Buenas, OK al nombre del fichero y al doble scroll.

En cuanto a lo de los públicos objetivos y el objeto del procedimiento, nos sigue funcionando igual:

![image](https://github.com/GovernIB/rolsac2/assets/44995350/2824087a-1f28-4688-ba49-726cd0da7c30)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/d865dfb2-2c77-48f6-9637-c77563d245d0)

**Comment by slromero-indra** [comment]
Respecto al publico objetivo y el objeto, se debe porque en libreoffice/openoffice, se selecciona las opciones de coma como separador. Debería de seleccionarse sólo la opción de punto y coma. Por favor, confirmarnos si con punto y coma funciona correctamente:

![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/8bb02268-b746-400d-b33c-f0e9a00a1a62)

**Comment by scalafat-dgtic** [comment]
Confirmado que funciona con punto y coma. 

Cierro
