### ISSUE TITLE
OAE - Replegar/desplegar las ventanas de módulos en modales

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#129]
Se pide poder minimizar/desplegar los módulos situados a la derecha para reducir saturación.

![image](https://github.com/GovernIB/rolsac2/assets/44995350/fc636a5d-4306-44a4-8aea-6eae3780fcbb)

También se pide que, si está desplegado, también se vean todos los elementos sin que haya una barra de desplazamiento.

![image](https://github.com/GovernIB/rolsac2/assets/44995350/24dca7d6-b31a-4ceb-b826-13553775f881)

**Comment by slromero-indra** [comment]
Hemos observado que en algunos casos, si hay muchos elementos, puede que la navegación lateral se haga muy grande y sea un poco incómodo. Si os parece bien, hemos pensado en dejar el scroll como está ahora pero habrán 2 botones en la parte superior derecha, el botón - (con la misma función que comentáis) y el botón + (que eliminará el scroll como comentáis).

![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/fa0777d3-1986-4d53-9d5a-48b1af810027)

Si preferís sin el botón +, cambiamos el scroll como comentáis, sólo hay que tener en cuenta que en ciertos datos como procedimientos o servicios se puede producir un scroll muy grande a nivel del dialog.

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización, ¿lo podéis revisar?
