### ISSUE TITLE
OAE - Eliminar opción de visualización en módulos simples en modales

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#130]
Se pide eliminar la opción de visualización en módulos simples donde no aportan valor.

![image](https://github.com/GovernIB/rolsac2/assets/44995350/2301a320-2afc-4fcd-86d3-b4f90a8ef5c6)

En Procedimientos y Servicios, éstos serían: 
- Público Objetivo
- Materias relacionadas
- Tema

**Comment by dmadronal-indra** [comment]
Buenas hemos realizado una actualización, ¿lo podéis revisar?
