### ISSUE TITLE
OAE - Ocultar módulo Unidad Administrativa en Normativas

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#131]
Se pide ocultar módulo de Unidad Administrativa relacionada en la pantalla de Normativas.

Por defecto, se asigne siempre a la UA de Govern de les Illes Balears

![image](https://github.com/GovernIB/rolsac2/assets/44995350/9c4f0c1f-3cdd-4421-9c22-bf92da994ea5)

**Comment by slromero-indra** [comment]
Como todas las normativas estarán asociadas a la raíz de la entidad, actualizaremos la migración de normativas para que ignore las relaciones en ROLSAC1 y sólo lo asocie directamente a la raíz. También habrá que actualizar las evoluciones para que no migre las normativas.

**Comment by slromero-indra** [comment]
Hemos incluido todas las mejoras en el tag 17_1, por favor, cuando podáis lo validáis.
