### ISSUE TITLE
OAE - Reordenació camps pantalla Procediments

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#133]
Organització en apartats
- DADES SIA
- DADES DE PUBLICACIÓ
- DADES
- ÒRGANS
- DADES DE CONTACTE
- INFORMACIÓ SOBRE PROTECCIÓ DE DADES PERSONALS

Canvis de comportament:
- El camp Tipus (Comú/específic) no s'ha de veure des del Gestor (només Adm.Contingut)
- Els camps "Responsable del tractament" i "Drets" no han de ser editables
- Els camps "Finalitat" i "Destinari" han de ser editables per procediment (tot i que agafi el valor per defecte des de l'Adm.Entitat) i el valor final a emmagatzemar ha de ser el que modifiqui l'usuari.

Respecte l'ordre, les imatges següents marquen la disposició provisional canviada:

![image](https://github.com/GovernIB/rolsac2/assets/44995350/ab8b77cb-ed03-4e88-b2fa-90b3c8a70f6b)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/ad0f7f86-85aa-4fee-95f2-df8b029429f7)

**Comment by slromero-indra** [comment]
Se han subido los cambios en el tag rolsac-2.0-S18_1, podéis revisarlo?

**Comment by slromero-indra** [comment]
Hemos generado un tag nuevo [rolsac-2.0-S18_2 ](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S18_2) que reorganiza los módulos laterales, cuando podáis lo validáis
