### ISSUE TITLE
OAE - Reordenació de camps pantalla detall Tràmit de Procediment

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#135]
Organització en apartats

- DADES DE PUBLICACIÓ
- DADES
- ÒRGANS
- CANALS DE PRESENTACIÓ

Canvis de comportament:
- A "Canals de presentació", el check de "Telemàtic" ha de ser el primer i estar marcat, per defecte, amb el comportament corresponent.

Respecte l'ordre, les imatges següents marquen la disposició provisional canviada:
- canviar d'ordre els mòduls de la dreta
- el mòdul "Models" ha de ser obligatori si té el check de presencial (opcional si telemàtic)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/c4aa517a-e51d-4257-9e65-f7be8f129ee7)

Respecte a la pantalla de Model de Tràmit:
- Eliminar "de tràmit" en el títol
- El camp "Document" és obligatori
- El botó "Subir" ha de dir "Pujar"
![image](https://github.com/GovernIB/rolsac2/assets/44995350/c465d821-c6f0-438e-a950-f8a32772b629)

**Comment by slromero-indra** [comment]
Hemos incluido todas las mejoras en el tag 17_1, por favor, cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
Perdonau, no vàrem especificar que volíem mantenir el primer apartat "EDICIÓ TRÀMIT DEL PROCEDIMENT", el podríeu tornar a posar? Consideram que és una bona manera de trametre feedback.

La resta està bé.

**Comment by slromero-indra** [comment]
Subido los cambios en el tag [rolsac-2.0-S17_2 ](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S17_2), cuando podáis lo validáis.
