### ISSUE TITLE
Adm.Contingut - Normativa - Error en el camp número

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#137]
A l'hora de desar una normativa recentment importada de ROLSAC1, no la podem desar perquè bota un error de que el camp no és vàlid (sembla ser de tipus "integer" o així es deu fer la validació). Ho podeu modificar a tipus string?

![image](https://github.com/GovernIB/rolsac2/assets/44995350/7fabf3e3-d11f-4d3e-8b77-09b53acbcb47)

**Comment by slromero-indra** [comment]
Estamos revisando con rolsac1, si os parece correcto, comprobamos si mantiene el patrón NNNNN/YYYY (siendo de 1-5 caracteres el NNNNN mientras que el YYYY tienen que ser 4 caracteres) y, en caso de no seguir el patrón, dar el mismo mensaje que rolsac1:

![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/e8f59f74-f04e-4189-bcaf-609e24a66e14)

**Comment by scalafat-dgtic** [comment]
Ok a repetir patrón de ROLSAC1. 

Tal vez ayude poner en el placeholder del campo el formato así indicado (NNNNN/YYYY).
También pasa lo mismo con el número del boletín del BOIB
![image](https://github.com/GovernIB/rolsac2/assets/44995350/60bd22d8-019e-4476-8b4d-1ffd9cef331d)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/1be238f8-a665-498f-b8a9-fd311666b7a8)

**Comment by slromero-indra** [comment]
Hemos revisado rolsac y no se seguía ninguna máscara asociada al número boletín. 
Entiendo que la mascara de número boletín es XXX/YYYY siendo XXX de 1 a 3 dígitos y YYYY tiene que ser de 4 dígitos no?

**Comment by slromero-indra** [comment]
Hemos incluido todas las mejoras en el tag 17_1, por favor, cuando podáis lo validáis.
