### ISSUE TITLE
S18-4 Duplicar procedimientos y servicios

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#139]
En este punto se tratará la problemática de duplicar procedimientos y servicios. Se habilitará un nuevo botón que permita duplicarlos, seleccionando entre duplicar la versión en modificación o la versión definitiva

**Comment by slromero-indra** [comment]
Se han subido los cambios en el tag rolsac-2.0-S18_1, podéis revisarlo?
