### ISSUE TITLE
S18-2 Añadir campo versión en las evoluciones

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#141]
- En este punto se añadirá un input versión para indicar la versión actual, y se permitirá editarla, si nos encontramos en una de las siguientes evoluciones Básica, División, Competencias y Dependencia
- En el caso de la fusión no lo vemos necesario ya que se estará creando una nueva UA y ya se puede indicar la versión que corresponda.

**Comment by slromero-indra** [comment]
Se han subido los cambios en el tag rolsac-2.0-S18_1, podéis revisarlo?
