### ISSUE TITLE
API-REST incluir tiempos de respuesta en las diferentes funciones para permitir detectar problemas de rendimiento

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#143]
Se añadirá en el JSON de respuesta de las diferentes funciones, un nuevo campo que indicará el tiempo de ejecución de la función, de esta manera se podrán analizar aquellas funciones problemáticas

**Comment by slromero-indra** [comment]
Los cambios principalmente son los que hay en el commit https://github.com/GovernIB/rolsac2/commit/752358f10981203304707f942bafd0f9be5ffbc6 , en el módulo rolsac2-api-externa incorporando el tiempo de ejecución (campo que indica los milisegundos que cuesta ejecutar el dato):

![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/6c0618e8-d00e-4a83-bd32-dd4beb9cf0f9)

**Comment by slromero-indra** [comment]
Estos cambios están en el tag https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S20_1 asociados a todos los métodos del restapi que han sido adecuados al tema del tiempo, cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
Se pasan indicaciones a equipo SISTRA para que hagan las pruebas pertinentes.
En cuanto a ROLSAC2, cerramos.
