### ISSUE TITLE
Mejoras de rendimiento en el Backoffice

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#144]
- Inicialmente se revisarán las diferentes pantallas y se analizará que posibles mejoras son necesarias
- Con la información del punto anterior se añadirán índices necesarios para permitir mejorar la experiencia de usuario.
- Si estas mejoras no son suficientes se revisarán posibles alternativas

**Comment by slromero-indra** [comment]
Los cambios se han incluido en el tag [rolsac-2.0-S20_1](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S20_1) que incluye varios cambios ( a destacar mejoras en el árbol de unidades administrativas, mejoras en el coverter de procedimientos/normativas/servicios o los indicies).

También hay que ejecutar el fichero 05_INDEX.sql que incluye índices observados como muy importantes para ciertas consultas de visibilidad.

**Comment by scalafat-dgtic** [comment]
Se aprecia una mejora general de rendimiento, aunque seguiremos observando para comprobar posibles cuellos de botella
