### ISSUE TITLE
Cambiar color de checkboxes

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#147]
Cuando se selecciona una fila con un check, éste apenas se ve.

![image](https://github.com/GovernIB/rolsac2/assets/44995350/38ff60a5-7870-4563-8102-67249d7e71d2)

**Comment by slromero-indra** [comment]
En el tag [rolsac-2.0-S21_2](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S21_2) hemos incorporado los cambios que afectaba:
 - Las ventanas de evolución de UAs
 - Los temas de UAs y procedimientos.
Cuando podáis lo validáis.
