### ISSUE TITLE
OAE - Afegir camp a Procediments/Serveis d'email d'incidències 

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#149]
Arran de la problemàtica a l'hora de gestionar les incidències de tràmits telemàtics SISTRA 2 i d'adreçar-les al responsable del procediment/servei corresponent, i per tal de facilitar aquesta gestió, es demana afegir un quart camp a l'apartat DADES DE CONTACTE dels Procediments:
- "Correu electrònic per gestionar incidències (no visible a la Seu electrònica)" i que sigui **obligatori**. (aquest camp serà per emplenar amb el correu del responsable d'incidències funcionals)

**Comment by slromero-indra** [comment]
Este cambio sólo afecta a procedimientos o también a servicios?

**Comment by scalafat-dgtic** [comment]
me comentan que también para servicios, sí. Gracias!

**Comment by slromero-indra** [comment]
Incorporado en el tag [rolsac-2.0-S22_1](https://github.com/GovernIB/rolsac2/tree/rolsac-2.0-S22_1), cuando podáis lo validáis.
