### ISSUE TITLE
Adm.Contingut - Bloqueig en editar/consultar models de tràmit de procediment

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#151]
Quan es fa doble clic en la opció seleccionada es queda pensant i ja no es pot obrir cap més opció (ni les etiquetes, ni crear un nou model, etc). Si es fa clic al botó del llapis, va bé.

EDIT: Passa quan fas doble clic en qualsevol opció de les taules de la columna dreta

![image](https://github.com/GovernIB/rolsac2/assets/44995350/9fe86c83-09df-4024-9c45-150382fa43fd)

**Comment by scalafat-dgtic** [comment]
Segueix passant el mateix quan es fa doble clic en les opcions del Públic Objectiu.
OK a la resta

**Comment by slromero-indra** [comment]
En público objetivo, eliminaremos el error que hay en el evento doble click.

Actualmente no se puede acceder al detalle de público objetivo ya que entendemos que no aporta información relevante, es correcto?

**Comment by scalafat-dgtic** [comment]
correcto, se puede eliminar el evento doble click. Gracias!

**Comment by slromero-indra** [comment]
Ya está eliminado el bug en el evento doble click
