### ISSUE TITLE
OAE - Camps d'inserció de text ampliables

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#162]
Es sol·licita que els edittext de les pantalles dels formularis puguin ser 'estirats' per poder veure tota la informació, així com passa a ROLSAC1 (passar-los a 'textareas'??)

![Image](https://github.com/GovernIB/rolsac2/assets/44995350/1011231e-4677-402d-84f0-49bc46877526)

![Image](https://github.com/GovernIB/rolsac2/assets/44995350/706ad87b-cbe6-45ad-bb0b-142b796903e6)

**Comment by scalafat-dgtic** [comment]
Serán todos aquellos que se prevea que tendrán más de una línea. Por ahora, se detectan:
PROCEDIMIENTOS
- Nom del Procediment
- Objecte
- Destinataris
- Termini per a resoldre
- Observacions
- Finalitat
- Destinatari
- Drets

TRÁMITES de PROCEDIMIENTO
- Nom del tràmit
- Requisits
- Documentació a presentar
- Termini màxim
- Observacions
("Descripcions" dels Models i Documents relacionats)

SERVEIS
- Nom del Servei
- Objecte
- Destinataris
- Requisits
- Observacions
- Finalitat
- Destinatari
- Drets

NORMATIVA
- Títol de la normativa
- Enllaç a la norma

**Comment by slromero-indra** [comment]
Hemos actualizado los procedimientos:
![162_procedimientos_2](https://github.com/user-attachments/assets/6ceccba4-387a-46e2-96f9-c618711ce706)
![162_procediminetos_3](https://github.com/user-attachments/assets/5cd4569b-ce69-44a3-a287-99c55e5b8406)
![162_procedimientos](https://github.com/user-attachments/assets/00d23fb1-53c4-433e-9191-df0b46d271b8)

Los trámites:
![162_tramites](https://github.com/user-attachments/assets/5b132247-7fcc-4666-8710-10bfc14f4ec5)

Las normativas:
![162_normativas](https://github.com/user-attachments/assets/46d86234-8359-4a28-87c8-dfd9bed120da)

Los  servicios:
![162_servicios](https://github.com/user-attachments/assets/10b4d1cd-224a-4661-b631-0b7bbe5b92f6)
![162_servicios_2](https://github.com/user-attachments/assets/93c96bd8-47b5-46d0-8f99-acb0f04f7c3c)

Cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
OK a casi todo. 
En los trámites de los procedimientos, faltan los campos "Descripción" de los "Modelos" y los "Documentos relacionados"

**Comment by slromero-indra** [comment]
Hemos actualizado el campo descripción en los documentos de trámite, como de procedimientos y también de normativas. Cuando podáis lo validáis

**Comment by slromero-indra** [comment]
![imagen](https://github.com/user-attachments/assets/d03c42ab-7f45-4a1d-ba29-206ba157ac86)
