### ISSUE TITLE
OAE - Modificar info de LOPD

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#164]
- [ ] A la pantalla de procediments, en el cas de ser un procediment comú, que el camp "Responsable del tractament" posi: 
(ca) "L’òrgan directiu (direcció general o secretaria general) competent per a la tramitació del procediment/servei"
(es) "El órgano directivo (dirección general o secretaría general) competente para la tramitación del procedimiento/servicio"

- [ ] Desplegable "Legitimació" ha de tenir la opció per defecte "Compliment d’una missió realitzada en interès públic o en l’exercici de
poders públics."

**Comment by slromero-indra** [comment]
Comparte lógica con la issue #196 Además de actualizar el fichero 02_create_data.sql para que cuando se cree los datos desde 0 mantenga los valores que se piden en la issue, hay que ejecutar lo siguiente:
```

 UPDATE RS2_TIPOLEG SET TPLE_DEFECT = 0;
UPDATE RS2_TIPOLEG SET TPLE_DEFECT = 1 WHERE TPLE_IDENTI LIKE 'CUMPLIMIENTO_MISION';
COMMIT;


UPDATE  RS2_TRAENT SET TREN_UACOMU = 'L''òrgan directiu (direcció general o secretaria general) competent per a la tramitació del procediment/servei' WHERE TREN_CODENT = 1 AND TREN_IDIOMA = 'ca';
UPDATE  RS2_TRAENT SET TREN_UACOMU = 'El órgano directivo (dirección general o secretaría general) competente para la tramitación del procedimiento/servicio' WHERE TREN_CODENT = 1 AND TREN_IDIOMA = 'es';
commit;
```
