### ISSUE TITLE
OAE - Obligatorietat de presentar "documents relacionats" en els dos idiomes

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#165]
A la pantalla de Procediments, Serveis (i a la pantalla dels tràmits del procediment), la presentació de "Documents relacionats" no és obligatòria, però si es vol presentar un document, s'ha de validar que es presentin els documents en tots els idiomes (ara mateix, només es valida el títol)

![Image](https://github.com/GovernIB/rolsac2/assets/44995350/89a2986f-19cd-43fc-a01f-1c443028f545)

**Comment by slromero-indra** [comment]
En los servicios también hay posibilidad de añadir documentos, se tendría que añadir también en servicios, no?

**Comment by scalafat-dgtic** [comment]
Correcto, también

**Comment by slromero-indra** [comment]
Ya están subidos los cambios, cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
Corregir el mensaje de error, traducido en cada idioma, que indique que se debe añadir documento en cada idioma:

"Ha d'afegir un document per cada idioma"
"Debe añadir un documento para cada idioma"

**Comment by slromero-indra** [comment]
Actualizado los literales en el commit, cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
El campo "Document" no debe ser obligatorio (con la última subida, ahora lo es) pero cuando se sube un documento en un idioma, también se debe subir en los demás idiomas.

**Comment by slromero-indra** [comment]
Disculpad, lo cambiamos, entiendo que es o no se sube ningún documento o el documento en todos los idiomas. Además, este cambio afectará tanto a documento de procedimiento, de trámite y de servicio.

**Comment by scalafat-dgtic** [comment]
Correcto todo. Gracias

**Comment by slromero-indra** [comment]
Actualizado el ultimo cambio, cuando podáis lo validáis.
