### ISSUE TITLE
OAE - Només s'han de poder assignar normatives vigents als procediments

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#179]
A l'hora d'assignar una normativa a un procediment, només s'han de poder seleccionar les vigents. En les captures s'ha creat una normativa derogada i es poden acabar assignant a un procediment

![Image](https://github.com/GovernIB/rolsac2/assets/44995350/4c71fd2d-092a-4e65-ad0b-2abc979a2852)

![Image](https://github.com/GovernIB/rolsac2/assets/44995350/5fe88e8c-3f6b-4fd6-89f3-0668af9d138d)

**Comment by slromero-indra** [comment]
Hemos actualizado la aplicación, cuando podáis y lo validáis.
