### ISSUE TITLE
S3-3 CLASIFICACION TEMÁTICA

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac2#18]

**Comment by bgarcia-dgtic** [comment]
Se prevé la creación del mantenimiento básico  de clasificación temática, basándose en su estructura de árbol, con los datos planteados en el modelo de BBDD.  La asignación de elementos relacionados (clasificación para ua, normativas, etc..) se planteará con posterioridad a la tarea S3-10 y se abordará en próximos ciclos.

**Comment by bgarcia-dgtic** [comment]
No hi ha relació amb matèries SIA.

**Comment by bgarcia-dgtic** [comment]
De moment ho deixam per separat
