### ISSUE TITLE
OAE - Simplificar la pujada de documents (canviar component FileUpload)

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#183]
Sol·liciten modificar tots els components FileUpload (a "documents relacionats", "Documents LOPD", als models del tràmit del procediment...) per una pujada de fitxer simple (o [múltiple](https://www.primefaces.org/showcase/ui/file/upload/basic.xhtml?jfwid=7606a), però que sigui prémer un botó).

![Image](https://github.com/GovernIB/rolsac2/assets/44995350/b0f91d17-216c-4f4d-845b-0e2150e50384)

**Comment by slromero-indra** [comment]
Ya están subidos los cambios, cuando podáis lo validáis.
