### ISSUE TITLE
Actualització versió de Primefaces

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#184]
Es detecten les següents modificacions necessàries per passar de Primefaces 8 a la 14:
- TABLAS:
o   Uso de nuevos métodos para la paginación
o   Actualización métodos para obtener y permitir filtrar y reordenar columnas
o   se modifica la manera en la que se obtienen los datos de paginación.

- Revisión completa de estilos (revisión de todas las pantallas):
o   Se han actualizado los iconos y como obtenerlos
o   Revisión de estilos en todas las pantallas ya que se css grid queda deprecated y habrá que usar primeflex
o   Revisión descuadres y tamaños

- Subida de ficheros mediante FileUploaded (veure #183) : Es necesario revisar la manera en que se suben los ficheros, ya que hay nuevos métodos que son necesarios usar.

- Revisión de métodos deprecated que han sido eliminados en el los xhtml(por ejemplo p:repeat), habrá que migrarlos a los nuevos componentes.

- Graficas: hay que rehacer todas las gráficas para adaptarlas al nuevo modelo.

**Comment by slromero-indra** [comment]
Ya están subidos los cambios, estamos terminando unos pequeños bugs gráficos visuales, en breve subiremos nuevos cambios.

**Comment by slromero-indra** [comment]
Ya están subidos todos los cambios para actualizar la interfaz gráfica a la versión 14 de primefaces. Cuando podías lo validáis

**Comment by scalafat-dgtic** [comment]
Entendemos que está correcto,. A tener en cuenta #183 para futuros sprints.
