### ISSUE TITLE
Error al crear "nueva normativa"

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#185]
Después de resolver el issue #106, al pulsar sobre "Nou" para crear una nueva normativa, **si antes se ha visualizado una normativa** (y comprobar el funcionamiento de #106), se realiza una búsqueda por defecto por normativa derogada.

![GIF 31-07-2024 09-36-43](https://github.com/user-attachments/assets/a1569f47-f323-432d-9b0b-30ee14239544)

**Comment by slromero-indra** [comment]
Cambios subidos, cuando podáis lo validáis
