### ISSUE TITLE
S3-4 NAVEGACIÓN MIGA PAN + NAVEGACIÓN ORGANIGRAMA

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac2#19]

**Comment by bgarcia-dgtic** [comment]
Se prevé la funcionalidad que permita, en función del elemento seleccionado en la miga de pan, mostrar sus elementos relacionados. También se prevé añadir un filtro avanzado (check box o similar) que permita indicar si buscar únicamente en el elemento actual o incluir en la búsqueda de elementos los elementos pertenecientes a los hijos

**Comment by bgarcia-dgtic** [comment]
Falta permetre actualitzar la resta d'elements (serveis, procediments, fitxes, etc.), i la creació del filtre avançat per a la cerca a les UAs filles.
