### ISSUE TITLE
Error en cercador de Procediments i Serveis

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#190]
Quan es prem el botó de l'ull al camp "Públic Objectiu":

![Image](https://github.com/user-attachments/assets/45ae4c0d-f939-4a74-9cf6-cdc6f19a43b3)

**Comment by slromero-indra** [comment]
El commit bueno es este : https://github.com/GovernIB/rolsac2/commit/6f62bcb1476c279e5e0fbd7ab60bc880ac61a0a3 

Cuando podáis lo validais, soluciona el problema.

**Comment by scalafat-dgtic** [comment]
Se ha colado, o se coló en su momento, un "XX2" en el fichero "dialogSeleccionTipoPublicoObjetivoEntidad"

![image](https://github.com/user-attachments/assets/d83358e3-7e30-4ca1-b454-e9762c56fbf0)

**Comment by slromero-indra** [comment]
Disculpad, borrado el XX2 que se había colado.
