### ISSUE TITLE
Cercador de Procediments/Serveis - plantilla tràmit desconegut

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#191]
Apareix una plantilla tràmit que no es troba definida en l'administrador d'Entitat

![Image](https://github.com/user-attachments/assets/95759d86-543a-4592-ac84-c19f122e9187)

**Comment by slromero-indra** [comment]
Hemos realizado los cambios para quitar la plantilla sobrante, cuando podáis lo validáis.
