### ISSUE TITLE
OAE - Desplegable legitimació (opció per defecte)

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#196]
Canviar opció per defecte, en els procediments i serveis del desplegable "Legitimació" per què sigui l'opció: 

"Compliment d'una missió realitzada en interès públic o en l'exercici de poders públics"

**Comment by slromero-indra** [comment]
Comparte lógica con la issue #164. Además de modificar el 02_create_data.sql para que tenga por defecto la legimitación COMPLIMENT, hay que ejecutar la siguiente sql para que lo actualice con la versión actual:
```

UPDATE RS2_TIPOLEG SET TPLE_DEFECT = 0;
UPDATE RS2_TIPOLEG SET TPLE_DEFECT = 1 WHERE TPLE_IDENTI LIKE 'CUMPLIMIENTO_MISION';
COMMIT;

```
