### ISSUE TITLE
Error de comportament a Tràmits Procediments - Quan es tanca modal, es desa

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#197]
Una vegada es crea un Model o un Document relacionat i es guarda correctament, quan es modifica novament i, enlloc de Desar ho tancam, es guarda igualment i no salta cap comprovació de camps obligatoris.

(Tancar no hauria de guardar els canvis).

A més, s'ha de treure l'asterisc del camp "Descripció * " atès que no és obligatori.

(català)
![Image](https://github.com/user-attachments/assets/3c905fc6-2f76-473c-a020-ff337b4798d3)

(castellà)
![Image](https://github.com/user-attachments/assets/3a766f2e-942e-499d-bdc2-fd33e295c4af)

**Comment by slromero-indra** [comment]
Ya están subidos los cambios, cuando podáis lo validáis.
