### ISSUE TITLE
Error en traspàs de normativa BOIB

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#199]
En traspassar normativa del BOIB, el camp Número hauria de ser el número que apareix en el títol de la normativa. P ex: si es traspassa la normativa "Ordre 21/2024 de 2 de juliol..." el camp Número ha de ser "21/2024".

Si es pot traspassar tant el Número com el Tipus de Normativa ("Ordre" en el cas anterior), perfecte. Si no, que es quedi en blanc però que no posi un número que no és el correcte (apart de que no compleix el format del camp)

**Comment by slromero-indra** [comment]
Ya están subidos los cambios, cuando podáis lo validáis.
