### ISSUE TITLE
S3-6 GESTION FICHEROS

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac2#21]

**Comment by bgarcia-dgtic** [comment]
Se prevé tener la creación de un componente que permita la realizar la acción de subir ficheros y almacenarlos. Además de incluir la lógica interna de la aplicación que permita tratarlos. La asignación de estos ficheros en las diferentes pantallas (logotipos, documentos, fotos, etc…) se planteará con posterioridad a la tarea S3-10 y se abordará en próximos ciclos.
