### ISSUE TITLE
S3-8 MEJORAS EN LA GESTION DE IDIOMAS

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac2#23]

**Comment by bgarcia-dgtic** [comment]
Se prevé tener las mejoras tratadas en relación a la mejora de idiomas:

- Eliminación del antiguo desplegable de idioma en todos los dialogs y Creación de la nueva barra superior que permita la selección del idioma.
- Modificación del componente de selección de idiomas (botón con etiqueta que aparece en los campos traducibles, y el dialogo que  abre) para que permita tener en cuenta si quedan traducciones por introducir, y muestre la etiqueta de un color diferente.
- Actualización del componente en todas los campos de idioma.
