### ISSUE TITLE
S3-9 MEJORAS PANTALLAS

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#24]
Se prevé realizar los siguientes cambios sobre todas las pantallas

- Al pulsar Doble click sobre un elemento de una tabla, abrir el dialog en modo edición

- Actualizar títulos de los dialogs para tener uniformidad.

- Refrescar los labels al cambiar el idioma principal de la aplicación

- Revisar comportamiento idioma tipo media edificio (desaparecen campos al cambiar de idioma)

- Cambiar botones del componente idioma por Aceptar-Cancelar

- Revisar errores y pasar los que no sean error a Debug.

**Comment by bgarcia-dgtic** [comment]
Els títols dels popups dels camps muntilidioma, no son correctes. Apareix el text "Gestión de literales" en lloc del camp al que fa referència.
Solapament de submenús desplegables.
![imatge](https://user-images.githubusercontent.com/26536678/194243990-bb86b3ef-fe22-411e-b8c4-51eb4caab26a.png)
