### ISSUE TITLE
S4-1 MODIFICAR MANTENIMENT PÚBLIC OBJECTIU

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#26]
- Crear nova taula “públic objectiu” per entitat, que estigui relacionada amb la taula públic objectiu SIA. Cada PO de l'entitat només podrà estar relacionada amb un únic PO-sia

- Crear nova opció de menú a nivell d'administrador d'entitat

**Comment by scalafat-dgtic** [comment]
1. Canvi literals:
- Títol: "Públic Objectiu Entitat" per "Públic objectiu" 
- Columna taula: "Públic Objectiu Entitat" per "Públic objectiu SIA"

2. Diàleg de edició/creació: 
- Títol diàleg: "Detall de Públic objectiu"
- Camp "Identificador" no està marcat com obligatori: no hi ha validació ni tampoc té asterisc (*) a l'etiqueta. Si s'insereix amb valor buit, dona NullPointerException
- Si existeix un idioma obligatori no marcat (sense color vermell) i després es marca en vermell, la validació del camp multidioma Descripció permet "Desar" tot i tenir l'etiqueta vermella. Si entres a l'edició del text multidioma sí es valida.

3. Si s'elimina una fila de la taula de Públic Objectiu, no hi ha growl de confirmació.
4. El filtre de cerca no està implementat.

**Comment by jcerdar-indra** [comment]
Se resuelven los puntos comentados en: https://github.com/GovernIB/rolsac2/issues/26#issuecomment-1311653048 en los commits 20effc8 y 39e7e62
