### ISSUE TITLE
S4-2 INCLOURE IDIOMA EN CONFIGURACIÓ D'ENTITAT

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#27]
S'afegiran per a cada entitat dues llistes d'idiomes.

- Idiomes permesos

- Idiomes obligatoris

S'hi afegirà un desplegable per indicar l'idioma per defecte a l'API

- Es permetrà indicar el logo i la descripció

**Comment by scalafat-dgtic** [comment]
1. Deixar la configuració de l'entitat, quant a idiomes, només a "Configuració d'entitat" dins Administrador d'Entitat. Per tant, eliminar el duplicat de configuració d'idioma de la pantalla de SuperAdministrador.

![image](https://user-images.githubusercontent.com/44995350/201342933-7a067fb9-91fa-4b1f-8e92-c9b7a9bed051.png)

(Es posposa el manteniment bàsic d'idioma per no ser prioritari)

2. En afegir un Logo, si s'accedeix a l'Administrador d'Entitat peta. Pot ser un problema de paths absoluts i relatius?

_2022-11-07 13:33:41,240 SEVERE [org.primefaces.application.exceptionhandler.PrimeExceptionHandler] (default task-238) null: es.caib.rolsac2.service.exception.FicheroExternoException: Error al acceder al fichero 65 con path /app/caib/rolsac2/arxius\1\entidad\image (2).png  /app/caib/rolsac2/arxius\1\entidad\image (2).png (No existe el fichero o el directorio)_

**Comment by jcerdar-indra** [comment]
Se resuelven los dos puntos del comentario: https://github.com/GovernIB/rolsac2/issues/27#issuecomment-1311659229 a partir del último commit de la rama (00784aea7af8675471fc5ce3ca4273b7c686181c)

**Comment by scalafat-dgtic** [comment]
Faltaría mantenimiento idioma (para más tarde)
Estaría bien tener un poco de feedback en formato growl de confirmación al añadir un logo.
El resto OK

**Comment by slromero-indra** [comment]
Buenas, hemos revisado el punto del growl del idioma, ya lo podéis verificar.

**Comment by scalafat-dgtic** [comment]
El growl está OK pero está situado en la parte inferior derecha (casi no lo he visto). ¿Se podría colocar en la parte superior? p.ej: en la derecha

**Comment by jcerdar-indra** [comment]
En le tag [rolsac2-2.0-S8_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_1) se añade el growl en la parte superior derecha para este caso.
