### ISSUE TITLE
S4-3 ACTUALITZAR COMPONENT LITERALS TRADUïBLES 

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#28]
En funció de la configuració important s'aplicaran diferents colors a les etiquetes

- Verd: tots els idiomes emplenats
- Groc: falta algun idioma no obligatori
- Vermell: Falta algun idioma obligatori

**Comment by scalafat-dgtic** [comment]
L'etiqueta no refresca el color correctament en diferents casos. Per exemple, a Administrador d'Entitat -> Tipus de Procediment, tenim Català/Castellà/Italià com obligatoris (veure foto), només tenim omplerts Català/Castellà i ens surt de color verd

![image](https://user-images.githubusercontent.com/44995350/201345178-5376b63f-e375-44f8-8240-11ea2237220d.png)

![image](https://user-images.githubusercontent.com/44995350/201345390-691ea9e8-1534-4885-b9cc-adf1122b7b57.png)


![image](https://user-images.githubusercontent.com/44995350/201345356-4a0d90fa-37c3-4929-a7ec-82209aa597ca.png)
