### ISSUE TITLE
S4-4 PROCEDIMIENTS

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#29]
- Es crearà la finestra de procediments bàsica segons el nou estil enviat
- Es crearà el manteniment de tipus procediments i es permetrà assignar el tipus a aquesta finestra.

**Comment by scalafat-dgtic** [comment]
1. Filtre de Cerca no implementada
2. Revisió de literals: a la taula, Códi SIA, Códi Dir3 SIA
3. Marcar obligatorietat en el camps "Nom_procediment", "forma de inici", "silenci", "tipus_procediment"....
4. Separar en un mòdul apart la informació de les dades SIA. (Hi hauria el mòdul de DADES, DADES SIA, DADES DE CONTACTE, INFORMACIÓ SOBRE PROTECCIÓ DE DADES...)
5. Dins diàleg: 
- "Nou Procediment" quan estic editant un procediment ja existent
- "Público Objectiu" en lloc de "Públic Objectiu"
6. Dins diàleg, dins "Tràmits":
- No entenem el CODI -1
- Revisar literals com: "Terme màxim" --> "Termini màxim"; "CANALES DE PRESENTACIÓ" --> "CANALS DE PRESENTACIÓ"; els checkboxes no estan traduïts (Telefónico)
- Només es valida el camp "Data de Publicació" com obligatori
- En "Desar", no es guarden els tràmits associats al Procediment
7. Dins diàleg, dins "Normatives":
- Ocultar columna Codi
8. Dins diàleg, dins "Matèries relacionades"
- Ocultar columnes Codi i Identificador
9. Dins diàleg, dins "Público Objectiu"
- Ocultar columnes codi, identificador i entitat (que hauria de filtrar-se per Entitat, d'entrada)
- No trobam coherència entre els noms de les columnes i la taula de la dreta que diu "Descripció", quina relació hi ha entre esquerra i dreta?
10. No estan implementats els mòduls de LOPD ni Documents relacionats

**Comment by slromero-indra** [comment]
Buenas, hemos revisado todos estos puntos, ya lo podéis verificar.

**Comment by episano-dgtic** [comment]
11. El backoffice no permite cambiar el orden de los documentos, trámites como rolsac1. Adicionamente tb. se debe incluir para el caso de las normativas
12. El buscador avanzado no busca en todos los campos del procedimiento/trámite y el check de buscar en unidades hijas no se aplica. 
13. He detectado problemas de visualización de los pop-up, Debo disminuir al 80% para que aparezca opción guardar. Haciendo que sólo se emplee el 50% de la pantalla. Adicionalmente hay casos que si muevo el pop-up hace que desaparezca la cabecera. 
![disminuirZOOM para pie](https://user-images.githubusercontent.com/17451683/212011395-291e9beb-36b5-4e71-8ae0-abdc580bb1fe.gif)
![zoom y movimiento](https://user-images.githubusercontent.com/17451683/212011430-0d109425-9f68-45ea-9913-ff57620c6299.gif)

**Comment by scalafat-dgtic** [comment]
1. En el popup de Procediments, les traduccions no agafen el valor d'origen dels Destinataris

![image](https://user-images.githubusercontent.com/44995350/217748906-ae8dddc6-912b-4fff-9388-7e8abb1f8870.png)

2. No entenem què vol dir "Habilitat apoderat" i "Habilitat funcionari". Cal substituir per "Disponible per apoderat" i "Permet actuació de Funcionari Habilitat"

![image](https://user-images.githubusercontent.com/44995350/217749036-f1861ab4-0218-4e1d-91d6-bd3e5c3b8b4a.png)

3. Prioritzar desplegable "Específic/Comú" (i que surti "Comú" per defecte) a la part superior: posar gran i que sigui dels primers camps.
4. El filtre simple no filtra per Estat
5. Falta revisar literal **Códi SIA per Codi SIA (també en el filtre avançat)
6. El botó '+' que obri el filtre avançat, ha de canviar quan es pitja per un signe '-'

**Comment by bgarcia-dgtic** [comment]
El check de "Habilitat apoderat" no funciona correctament. El missatge ha d'aparéixer en funció del públic objectiu "Administració" i no "Empleat públic".

**Comment by episano-dgtic** [comment]
8. Los desplegables de procedimientos si no caben, al moverse a bajo(scroll ratón) se mantienen posición absoluta pantalla y no se muestran completos.. 
![seleccionables_scroll](https://user-images.githubusercontent.com/17451683/218742254-0710d889-1ddb-49cf-b65e-442b3f361dff.gif)
9. El check "Disponible per apoderat" no identifica correctamente el PO Administraciones, haciendo lógica sea incorrecta. Adicionalmente para el público personas, empresas debe marcarse el check por defecto. Al igual que si se marca administraciones se debe desmarcar. 
10. Si trámite es solo telemático y está marcado funcionario habilitado, aparece el pop-up con 2 botones. Sólo debería haber un botón aceptar (confirmación lectura) pero no permita guardar hasta corriga el error. 
![funcionari_habilitado](https://user-images.githubusercontent.com/17451683/218747654-5ebb82f5-20f7-402a-aa37-35691d577214.png)
11. Se permite incluir imagenes como documento LOPD, deben ser pdf.

**Comment by episano-dgtic** [comment]
12. Se hecha en falta el "Òrgan competent per resoldre".

**Comment by episano-dgtic** [comment]
13. Respecto buscador avanzado procedimientos:
        Bolcado a sia (en lugar de un desplegable si o no, debería aparecer Activo, No activo o cap.).
	En el caso Públicos objectivos: Una vez aplicado un filtro, si modificas PO, no aparecen los filtros aplicados inicialmente. Adicionalmente si seleccionas previamente desde módulo (tema), aparece lo preseleccionado en el módulo de PO.
	
![modulo PO_con tematica](https://user-images.githubusercontent.com/17451683/220580360-1149575f-5547-411b-b8bc-f1ee5243587c.gif)
	
	Falta filtros:
		* fin de la via administrativa
		* trámite vigente		
		* trámite telemático
		* plantilla trámite
		* plataforma de tramitación
		* Para el administrador contenidos: Es común

Tampoco está el filtro de código procedimiento y código del trámite, aunque el buscador textual responde a estos.

**Comment by slromero-indra** [comment]
Buenas, se han comiteado varios cambios en el tag S7_4 (pero como faltan algunos detalles, mejor revisarlo en el próximo tag que subiremos próximamente de la S8_1).

 Tenemos varios dudas, comentasteis que debería de haber una manera sencilla que un adm. contenido y un gestor vean si tienen mensajes pendientes. A nivel interno tendrán dos datos que se guardará si tiene mensajes pendientes de leer el gestor o el supervisor. En la página principal de procedimientos/servicios, quitaremos las 2 columnas que comentasteis de SIA, añadiríamos una columna que indique si el gestor o supervisor (dependiendo el rol, se verá su columna correspondiente) tiene algún pensaje pendiente. Al lado del botón de buscar habrá un check:

![imagen](https://user-images.githubusercontent.com/17451407/222419482-367f5dee-d802-44a8-b719-9aadbc55c1e1.png)

**Comment by slromero-indra** [comment]
Respecto al punto 9, actualmente se utiliza el check de empleo público. Como los tipos de público objetivo son genéricos (se pueden crear tantos como se desee), añadiremos un check a nivel de publicos objetivo supervisor que indicará si es para administraciones. 

Al realizar dicho cambio, cuando se abra el desplegable de seleccionar públicos objetivos, sólo podrás elegir los que  sean del mismo tipo administraciones (o todo activo o ninguno). Dependiendo de lo seleccionado, se actualizará el disponible per apoderat.

**Comment by scalafat-dgtic** [comment]
Nuestra propuesta, a la espera de confirmación por parte de la OAE sería la siguiente.

![image](https://user-images.githubusercontent.com/44995350/223963138-6a6aeb82-1522-476e-8a65-4a19701fec3b.png)


Las columnas, que sean las mismas que la pantalla de Procedimientos de ROLSAC1, es decir, en este orden de izq a derecha:

1. Visibilidad (Si es visible, con icono de documento; si no es visible, con icono con el signo de prohibido)
2. Código
3. Estado del procedimiento
4. Nombre del procedimiento
5. Tipo de procedimiento
6. Fecha de actualización (o de última modificación). Por tanto, hay que añadir el campo a la tabla
7. Común/específico
8. Pendiente de leer (mediante icono de sobre cerrado/sobre abierto). Si son mensajes que debe leer el gestor con un asterisco naranja. Si son mensajes deben leer gestor y supervisor, con asteriscos azules y naranjas.

Además, se propone añadir el filtro del componente DataTable para facilitar el filtro simple: http://www.primefaces.org:8080/showcase/ui/data/datatable/filter.xhtml?jfwid=51445

**Comment by slromero-indra** [comment]
Buenas, hemos publicado en ibter una nueva versión con los cambios que comentáis, os parece correcto? Tenéis también los cambios en servicios (pero sin la columna de tipo procedimiento en servicios, que no es necesario). Hemos añadido a los comentarios anteriores también el estado del procedimiento (si está publicado/reservado/borrado o/y en modificación). Os pasamos una captura: 

![imagen](https://user-images.githubusercontent.com/17451407/224990087-d886ce75-7f7c-4c2f-bde7-027b40d1d25f.png)

Respecto al filtro, está asociado a la versión 11 de primefaces, por lo que tenemos que investigar si es factible en la versión de primefaces de rolsac2.

Respecto a la visibilidad, un procedimiento es visible si:
- Está publicado (en rolsac1, se miraba si era pública el campo validación) .
- El fecha de inicio del trámite de iniciación es anterior a la fecha actual.
- La fecha de cierre del trámite de iniciación es nulo o bien es posterior a la fecha actual.

También hay un detalle en la manera de mostrar la información en el listado (os lo comento por si en algún momento tenéis la duda sobre el funcionamiento). Actualmente, en el listado se muestra siempre el valor publicado ( en caso de no existir el dato publicado/reservado/borrado [el estado definitivo], entonces utiliza el dato en estado de modificación). Lo comento porque si tienes el dato publicado y en modificación y un campo es distinto (por ejemplo, el tipo de procedimiento) en el listado se ve sólo la información publicada.

**Comment by scalafat-dgtic** [comment]
La distribución de la pantalla de principal de Procedimientos/servicios la vemos bien (revisar formato fechas). No se modifica la fecha de actualización cada vez que realizamos un cambio de flujo/estado.

- En Servicios aparece el mensaje del funcionario habilitado al continuar. No debería aparecer el mensaje ni el control a ese nivel
- Al publicar un servicio, si queremos editarlo desde Gestor, no aparece el botón de Guardar

![image](https://user-images.githubusercontent.com/44995350/228244856-9aee248a-dc64-4a79-af2f-310adc64e1e2.png)

**Comment by scalafat-dgtic** [comment]
Tenemos errores al guardar nuevos trámites desde un Procedimiento

2023-04-20 09:40:25,125 ERROR [org.jboss.as.ejb3.invocation] (default task-10) WFLYEJB0034: Invocación EJB falló en el componente ProcedimientoServiceFacadeBean para el método public abstract void es.caib.rolsac2.service.facade.ProcedimientoServiceFacade.update(es.caib.rolsac2.service.model.ProcedimientoBaseDTO,es.caib.rolsac2.service.model.ProcedimientoBaseDTO,es.caib.rolsac2.service.model.types.TypePerfiles,java.lang.Long) throws es.caib.rolsac2.service.exception.RecursoNoEncontradoException: javax.ejb.EJBException: java.lang.NullPointerException
	at org.jboss.as.ejb3@7.2.0.GA-redhat-00005//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:246)

2023-04-20 09:40:25,134 WARNING [javax.enterprise.resource.webcontainer.jsf.lifecycle] (default task-10) #{dialogProcedimiento.guardar}: javax.ejb.EJBException: java.lang.NullPointerException: javax.faces.FacesException: #{dialogProcedimiento.guardar}: javax.ejb.EJBException: java.lang.NullPointerException
	at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:119)

Caused by: java.lang.NullPointerException
	at deployment.rolsac2.ear//es.caib.rolsac2.persistence.converter.TipoTramitacionConverter.convierteLiteralToTraduccion(TipoTramitacionConverter.java:65)
	at deployment.rolsac2.ear//es.caib.rolsac2.persistence.converter.TipoTramitacionConverterImpl.createEntity(TipoTramitacionConverterImpl.java:80)

**Comment by scalafat-dgtic** [comment]
Cerramos issue a la espera de revisión por parte de la OAE,  que la crearemos en backlog
