### ISSUE TITLE
S4-5 NORMATIVES

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#30]
- Es crearà la taula de documents relacionats per permetre fer l'upload d'aquests fitxers i afegir-hi les dades relacionades (títol, descripció, url, tipus de relació amb la normativa).
- S'actualitzarà la finestra de normatives al nou disseny

**Comment by scalafat-dgtic** [comment]
Dins diàleg:
1. Revisar literals de Detall Normativa (tot està en Castellà: DATOS, DATOS DE PUBLICACIÓN, DOCUMENTOS RELACIONADOS, UAs RELACIONADOS...)
2. Revisar validacions de camps obligatoris
3. No es pot editar un document relacionat ja creat
4. No funciona el guardat de fitxers en els documents relacionats
5. No es troben implementats els mòduls (UAs, Afectaciones...)
6. Els camps "Enlace a la norma" i "Responsable" limitat a 50 caràcters

A la taula principal:
1. No es filtren per Entitat

**Comment by jcerdar-indra** [comment]
Se resuelven los puntos del comentario: https://github.com/GovernIB/rolsac2/issues/30#issuecomment-1313250795 en el último commit de la rama (00784aea7af8675471fc5ce3ca4273b7c686181c)

**Comment by dmadronal-indra** [comment]
Matizar que el punto  "5 No es troben implementats els mòduls (UAs, Afectaciones...)" y "A la taula principal:    No es filtren per Entitat" se abordarán en este ciclo en una issue independiente ya que no están implementadas las relaciones con el resto de tablas. el resto de puntos están resueltos.

**Comment by scalafat-dgtic** [comment]
Ok, faltaría también
- Revisar literals de Detall Normativa --> DATOS

**Comment by slromero-indra** [comment]
Buenas, hemos revisado todos estos puntos, ya lo podéis verificar.

**Comment by scalafat-dgtic** [comment]
Ok a l'anterior.
Ara hem vist, al diàleg de creació/detall de normativa:
![image](https://user-images.githubusercontent.com/44995350/212009201-a85678a7-f188-4312-94d6-524ecba3381c.png)

1. Revisar literal "PROCEDIMIENTS relacionats"
2. No es mostren les afectacions que existeixen a BD
3. No estan implementades els procediments, serveis ni afectacions, però entenc que s'abordarà a l'issue independent que diu en @dmadronal-indra
