### ISSUE TITLE
S4-7 MILLORES PLATAFORMA

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#32]
- Actualitzar la molla de pa perquè en canviar d'element s'actualitzin les pàgines de personal i normatives.
- Actualitzar el component d'idioma perquè permeti un editor tinny als elements que corresponguin

**Comment by scalafat-dgtic** [comment]
1. En canviar de UA, no es refresca l'estat (veure Personal i Normatives)
2. En els editors HTML (tiny), quan es guarda un contingut, es mostren les etiquetes HTML (<p>...</p>)

![image](https://user-images.githubusercontent.com/44995350/201611388-d45c87e2-05f8-4638-8bdb-6428100edf1e.png)

**Comment by scalafat-dgtic** [comment]
A raíz de como queda el campo tiny, y como está quedando el de procedimientos (#33), creo que habría que 'sacar' el primer diálogo general de todos los mantenimientos.

Pasaremos propuesta

**Comment by scalafat-dgtic** [comment]
- Redimensionaria el popup com hem fet a Procediments
- Per donar més espai, podem posar els camps HTML a la línia següent (a l'esquerra, com a primer camp de la línia) i amb màxima amplitud
![image](https://user-images.githubusercontent.com/44995350/212015121-83e00315-4384-4942-a319-c4b53e50bc70.png)

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S7_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S7_1) se ha modificado el formulario de las Unidades Administrativas para que se muestren como se indica en el comentario anterior.
