### ISSUE TITLE
S5-1 GESTIÓ DEL FLUX EN PROCEDIMENTS I SERVEIS

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#33]
Es durà a terme una primera fase en què es començaran a abordar les pantalles implicades en el flux i la lògica interna per manejar-lo (duplicació d'estats del procediment/serveis). En finalitzar el cicle es preveu tenir la maquetació de les pantalles implicades i un flux de mock per veure'n el funcionament. (la finalització de la lògica completa es preveu al proper cicle)

**Comment by scalafat-dgtic** [comment]
- No hi ha res sobre serveis

- En el missatge del control de flux, no es poden ficar exclamacions (!) o altres caràcters.

- Diàlegs massa grossos i massa anidats. Passarem proposta de redistribució de diàlegs (veure #32 ) com ROLSAC1

- Es permet publicar sense tràmit d'inici.
- No es pot tornar enrera una vegada un procediment està publicat
- Falten camps a la gestió de procediments  (Objecto, destinatarios, Termini per resoldre i notificar, observaciones, etc)
- Segueix havent codis enlloc de descripcions

![image](https://user-images.githubusercontent.com/44995350/207531904-7de7aa1d-b2d4-41ad-b5f9-deb59d22bf5f.png)

**Comment by scalafat-dgtic** [comment]
- Redimensionar tots els diàlegs (per reduir l'impacte dels camps)
- Camp Legitimació té el codi i no la descripció

**Comment by slromero-indra** [comment]
Buenas, hemos revisado todos estos puntos, ya lo podéis verificar.
