### ISSUE TITLE
S5-2 GESTIÓ DE PROCESSOS AUTOMÀTICS

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#34]
Es durà a terme el desenvolupament del següent:

- 1 mestre detall per a la definició de processos.
- Creació d'una taula addicional sense manteniment que defineixi els tipus de processos (es farà a nivell de script BBDD, tant de creació d'estructura com de dades d'inici).
- 1 mestre detall per llistar els processos en execució.
- Afegir la lògica interna que permeti l'execució de processos.
- Definició d'una interfície genèrica per a l'execució de processos.
- Creació d'un procediment de mock per poder provar

**Comment by scalafat-dgtic** [comment]
- Afegir llançament de tasques programades (poder enviar job a un dia i hora específic)
- Falten integracions amb SIA o relació advertències d'enviament per procediment
- Poder cancelar jobs pendents

**Comment by bgarcia-dgtic** [comment]
El check de "Habilitat apoderat" no funciona correctament. El missatge ha d'aparéixer en funció del públic objectiu "Administració" i no "Empleat públic".

**Comment by scalafat-dgtic** [comment]
Perdonad, OK a lo comentado en el correo sobre no permitir dar de alta procesos automáticos que dependan de un plugin si ese plugin no está dado de alta

**Comment by jcerdar-indra** [comment]
Se añade validación para impedir dar de alta un proceso dependiente de un plugin si el plugin indicado no está dado de alta.

**Comment by scalafat-dgtic** [comment]
Intento dar de alta el proceso automático de sincronización con DIR3 y me indica que se necesita dar de alta el plugin de SIA (?)

![image](https://github.com/GovernIB/rolsac2/assets/44995350/99eebacd-2ac1-4acf-a8f4-92231357ba9c)

Si miramos en los plugins, además, el plugin de SIA (y el de DIR3) están dados de alta

![image](https://github.com/GovernIB/rolsac2/assets/44995350/6d09372b-08e2-478c-aed2-875c5d6f1656)

Estaría bien, también, incluir en el script de datos iniciales, dar de alta el proceso automático de DIR3 (para no tener que consultar el #72 )
