### ISSUE TITLE
S5-4 SERVEIS

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#36]
- Es crearà la pantalla de serveis administratius.
- S'hi afegirà l'assignació de públic objectiu.

**Comment by slromero-indra** [comment]
Buenas, hemos realizado la issue, ya lo podéis verificar.

**Comment by scalafat-dgtic** [comment]
Revisar literals (Codi SIA, Codi DIR3)

![image](https://user-images.githubusercontent.com/44995350/212045650-13e2722b-54cf-496d-a657-6f29634aa13e.png)


Diàleg
- Moure DADES SIA a la part superior
- Data de publicació obligatòria
- Els camps han de ser pràcticament els mateixos que a ROLSAC1 (eliminar Forma d'inici, silenci administratiu, etc. i afegir "Requisits", check de "Servei comú"....)

**Comment by jcerdar-indra** [comment]
Respecto a los comentarios de esta issue, hemos ido contestando punto a punto los temas que se han resuelto en el tag [rolsac2-2.0-S7_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S7_2). Los puntos que no se han comentado, son temas que estamos pendientes de revisarlos o actualizarlos en una próxima subida.

**Comment by scalafat-dgtic** [comment]
- Revisar literal **Códi SIA
- Falta afegir check de "Servei comú"
- Falta "Telèfon de contacte" a les "Dades de contacte"
- Arreglar doble scroll

![image](https://user-images.githubusercontent.com/44995350/217815987-1ba9f41a-55b2-4fd0-be7f-10d6f681454c.png)

- Falten les validacions de les associacions obligatòries dels serveis

**Comment by bgarcia-dgtic** [comment]
No permet guardar sense normatives. En els serveis, les normatives no són obligatòries.

**Comment by bgarcia-dgtic** [comment]
S'ha de modificar el literal dels títols dels diàlegs creació i edició del mòdul "Document relacionats". Fa referència a procediments en lloc de fer referència a serveis. 
![image](https://user-images.githubusercontent.com/26536678/218401375-aeefcfc9-7bf7-44c6-985e-9ccd276d17ea.png)

**Comment by episano-dgtic** [comment]
En el caso de los servicios no es obligatorio LOPD, en rolsac1 hay un check: 
![lopd_serveis_inactivo](https://user-images.githubusercontent.com/17451683/218751696-7a143457-f464-4d58-95aa-55ee1d0f2d85.gif)
Por defecto está activo, en la creación. 

Sólo se deben incluir pdf en para Documents informació sobre protecció de dades personals.

En esta versión no funciona el envio de mensajes para el perfil gestores.

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S8_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_2) se corrigen los distintos puntos comentados. Faltaría el tema del doble scroll que hemos detectado que se produce en Chrome y no en Firefox. En próximas revisiones lo resolveremos.

**Comment by scalafat-dgtic** [comment]
Si pitjam damunt 'Nou' servei i volem tancar el popup sense introduir res, ens bota la finestra de 'Canvis sense guardar' (que no tocaria perquè tot és buit i no hem tocat res) i quan li deim que volem continuar ens bota que falta omplir camps obligatoris. El que es vol és sortir sense tocar canvis, no hauria de fer comprovacions, i més si és a un Servei nou i es vol sortir.

![image](https://user-images.githubusercontent.com/44995350/224262771-372f4975-a681-427b-a2a6-86162579e36e.png)


En desactivar el check de "La informació de la LOPD està actiu" i guardar, quan es vol guardar però falten associacions obligatòries per omplir, el check continua desmarcat però tornen a aparèixer els camps de LOPD

![image](https://user-images.githubusercontent.com/44995350/224264054-603d9675-e41d-4029-a445-571770599958.png)

**Comment by scalafat-dgtic** [comment]
Ok als temes comentats.

A dalt a la dreta de la taula, s'haurien de deshabilitar els botons de "Editar" i "Esborrar" quan no hi ha cap element seleccionat (sobretot quan no hi ha dades) perquè me permet anar al popup de "Està segur que vol eliminar?" quan no he seleccionat res.

![image](https://user-images.githubusercontent.com/44995350/232461184-d7e73d46-57fa-47a8-a200-faedf1e0cc74.png)

**Comment by scalafat-dgtic** [comment]
He anat a crear un Servei nou i en haver omplert tots els camps obligatoris i pitjar Desar m'ha avisat de que faltaven les traduccions. En pitjar sobre Traduir m'ha sortit el següent error

![image](https://user-images.githubusercontent.com/44995350/232984366-e9a71a6c-2e61-43f9-9977-f82d3560a789.png)

2023-04-19 08:21:08,365 WARNING [javax.enterprise.resource.webcontainer.jsf.lifecycle] (default task-124) #{dialogTraduccion.load}: java.lang.NullPointerException: javax.faces.FacesException: #{dialogTraduccion.load}: java.lang.NullPointerException
	at com.sun.jsf-impl@2.3.5.SP2-redhat-00001//com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:119)
	at deployment.rolsac2.ear.rolsac2-back.war//org.primefaces.application.DialogActionListener.processAction(DialogActionListener.java:54)
	at deployment.rolsac2.ear.rolsac2-back.war//org.primefaces.application.DialogActionListener.processAction(DialogActionListener.java:54)
	at javax.faces.api@2.3.5.SP1-redhat-1//javax.faces.component.UIViewAction.broadcast(UIViewAction.java:587)

Caused by: javax.faces.el.EvaluationException: java.lang.NullPointerException
	at javax.faces.api@2.3.5.SP1-redhat-1//javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:101)

Caused by: java.lang.NullPointerException
	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.maestras.DialogTraduccion.imprimirLiteralesServicio(DialogTraduccion.java:282)
	at deployment.rolsac2.ear.rolsac2-back.war//es.caib.rolsac2.back.controller.maestras.DialogTraduccion.load(DialogTraduccion.java:99)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by slromero-indra** [comment]
Subido en el tag rolsac2-2.0-S9_2

**Comment by slromero-indra** [comment]
Subido en el tag rolsac2-2.0-S9_2

**Comment by scalafat-dgtic** [comment]
Ahora al rellenar campos del nuevo servicio, cuando le damos al check Presencial del Canal de Presentación, parece que toda la ventana cae para abajo sin opción a poder subir. Por eso, no podemos probar si la ventana de traducción se abre correctamente.

En la captura se ve donde nos quedamos. Si intentamos tirar para arriba, no se mueve.

![image](https://user-images.githubusercontent.com/44995350/233272768-b5694c21-3dc0-48ba-903b-c8e4b1bd9387.png)

**Comment by slromero-indra** [comment]
Los cambios que solucionan el problema en chrome están añadidos en el tag https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_5

**Comment by scalafat-dgtic** [comment]
Faltaría revisar

"A dalt a la dreta de la taula, s'haurien de deshabilitar els botons de "Editar" i "Esborrar" quan no hi ha cap element seleccionat (sobretot quan no hi ha dades) perquè me permet anar al popup de "Està segur que vol eliminar?" quan no he seleccionat res."

**Comment by jcerdar-indra** [comment]
Se deshabilitan botones de "Editar" y "Borrar" cuando no se ha seleccionado ningún elemento.

**Comment by scalafat-dgtic** [comment]
Veo que ahora tenemos el botón de Consultar que está desmarcado cuando seleccionamos un servicio

![image](https://github.com/GovernIB/rolsac2/assets/44995350/06da5113-5035-45fd-9728-b19f3781af64)

Lo dejamos para revisión final y cierro incidencia
