### ISSUE TITLE
S5-7 REVISIÓ PROBLEMES COMPONENT SELECCIÓ UA

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#39]
- Aquest component es revisarà per tractar els problemes d'extrema lentitud.
- Es realitzarà el filtratge en funció de la ua seleccionada a la molla de pa per a les normatives els procediments i els serveis)

**Comment by jcerdar-indra** [comment]
Los problemas de rendimiento asociados a esta issue se solucionaron durante el Sprint 5. ¿Se podría cerrar la siguiente issue o necesitáis que revisemos algo más al respecto?
