### ISSUE TITLE
S5-8 ACABAR ASSIGNACIONS DE PROCEDIMENTS

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#40]
- Es realitzaran les assignacions de Normatives, Documents relacionats.
- Es crearà el manteniment de tràmits i les corresponents assignacions d'elements.

**Comment by scalafat-dgtic** [comment]
Com s'ha comentat a altres issues (#32 i #33), hi ha massa coses dins el diàleg, millor treure'l defora imitant ROLSAC1 (ja concretarem)
- Una vegada el procediment està publicat, com que no es pot modificar, no es pot modificar cap assignació.

- Apartat de tràmits:
1. En l'addició de tràmits, el canal presencial activa el camp URL (hauria de passar només en el telemàtic)
2. En l'addició de tràmits, no hi ha control de dates (es pot publicar un tràmit abans del procediment)
3. En l'addició de tràmits, en l'addició de models, els títols posen "Nou Document de Procediment" amb els mateixos camps (falta actualitzar el títol del diàleg?)
4. Si s'omplen dades tramitació personalitzada, s'obliga a incloure paràmetres (està com obligatori) quan ha de ser opcional.
5. Si s'empra plantilla tràmit, en visualitzar no està marcada la opció telemàtica
6. Falta lògica habitual ROLSAC. Ex: - Se permeten varis tràmits d'inici. - Si és presencial no s'exigeix que s'incloguin models
7. No es poden modificar tràmits una vegada creats.
8. Calen modificacions de camps en els tràmits (falten requisitos, observaciones i sobra objecte, etc. --> revisar bé)

- Problemes de permisos a l'hora d'editar documents relacionats

![image](https://user-images.githubusercontent.com/44995350/207532197-b337d6b0-5b4f-42d2-b142-5d803cbf935f.png)

**Comment by slromero-indra** [comment]
Buenas, hemos revisado todos estos puntos, ya lo podéis verificar.

**Comment by episano-dgtic** [comment]
Lo comentado S4-4 La URL trámite telemático sigue exigiéndola, si personalizas sistra. Por otro lado, si sólo quieres rellenar URL no debe exigir la personalización de sistra.

Y detecto otro error, cuando inicialmente indico plantilla y luego trato de personalizar al guardar procedimiento:
Error intern S'ha produit un error: java.lang.IllegalStateException: org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : es.caib.rolsac2.persistence.model.JProcedimientoTramite.tipoTramitacion -> es.caib.rolsac2.persistence.model.JTipoTramitacion





[14:53](https://dgmadserveide-y8j9862.slack.com/archives/G010MH1ECJ1/p1673445216921929)
cuando personalizo tramitación, pero al modificarla de plantilla a personalizada

**Comment by jcerdar-indra** [comment]
-Respecto a los comentarios de esta issue, hemos ido contestando punto a punto los temas que se han resuelto en el tag [rolsac2-2.0-S7_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S7_2). 

Faltaría el siguiente punto: _Lo comentado S4-4 La URL trámite telemático sigue exigiéndola, si personalizas sistra. Por otro lado, si sólo quieres rellenar URL no debe exigir la personalización de sistra._ , el cual corregiremos y actualizaremos en la próxima actualización de ROLSAC2.

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S8_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_2) se corrige el tema de la obligatoriedad de la URL en los trámites telemáticos.

**Comment by scalafat-dgtic** [comment]
Seguim tenint problemes en la validació

![image](https://user-images.githubusercontent.com/44995350/224299371-95f5a4cc-77fb-46e8-9856-950fc0ad3b10.png)
