### ISSUE TITLE
S6-1 SERVEIS

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#41]
Es crearà la finestra de serveis i s'hi afegiran les assignacions corresponents.

**Comment by slromero-indra** [comment]
Buenas, hemos realizado la issue, ya lo podéis verificar.

**Comment by scalafat-dgtic** [comment]
Revisar #36

**Comment by jcerdar-indra** [comment]
> Revisar #36

En la issue #36 se indican las correcciones realizadas.

**Comment by scalafat-dgtic** [comment]
Revisar de nuevo

**Comment by jcerdar-indra** [comment]
Comentario añadido en la #36

**Comment by jcerdar-indra** [comment]
Los comentarios de la issue #36 se resuelven en el tag [rolsac2-2.0-S9_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_1)

**Comment by scalafat-dgtic** [comment]
Se tanca issue per seguir en el #36
