### ISSUE TITLE
S6-2 FINALITZAR LA GESTIÓ FLUX PROC/SERV

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#42]
Es finalitzarà la secció de flux i es permetrà afegir missatges a cada pas del flux tant per a procediments com per a serveis.

**Comment by slromero-indra** [comment]
Buenas, hemos realizado la issue, ya lo podéis verificar.

**Comment by scalafat-dgtic** [comment]
- Quan un gestor obri un procediment en estat publicat i el tanca sense tocar res, aquest procediment modifica el seu estat per "Publicat i en modificació". Entenem que aquest estat només hauria d'aparèixer mentre un gestor l'estigui modificant, no quan ja ha sortit sense guardar

**Comment by slromero-indra** [comment]
Los cambios para resolver la issue están incluidas en el tag rolsac2-2.0-S7_2.

Ahora, si el procedimiento/servicio tiene sólo el dato en estado publicado, al editar, saldrá un mensaje avisando si quiere continuar y crear datos en estado modificado a partir del dato publicado.

Respecto al tema en envío de emails, debido al coste de realizar, se pospone para más adelante. Los textos de la LOPD están en la configuración de entidad (aunque se ha comentado en otra issue de cambiarlo a una ventana separada).

**Comment by jcerdar-indra** [comment]
Esta tarea ya está realizada. Ahora mismo, cuando se va a un flujo pendiente o se viene de un flujo pendiente, se genera un mensaje automático. 
Este mensaje se extrae de unas properties en el fichero de rolsac2.properties (por ejemplo, el mensaje automático cuando se pasa de modificación a pendiente publicar), ¿ queréis queen vez de properties añadamos estos literales en alguna pestaña de configuración de entidad?

Los properties los podéis localizar en el siguiente fichero: https://github.com/GovernIB/rolsac2/blob/rolsac-2.0/scripts/configuracio/rolsac2.properties

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S9_5](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_5) se solucionan los errores comentados en el último comentario.

**Comment by bgarcia-dgtic** [comment]
A l'hora de marcar un missatge com a llegit, dóna error. Us he passat l'error per correu

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S10_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S10_2) se soluciona el error relacionado con los mensajes. Ahora se ha añadido un filtro para que, en caso de que se añada un apóstrofo en el mensaje, se adapte el mensaje para su guardado en BBDD.
