### ISSUE TITLE
S6-3 FINESTRA DE TRASPÀS EBOIB

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#43]
Es crearà la finestra que permeti incorporar una normativa recuperada des del connector d'eboib.

**Comment by slromero-indra** [comment]
Buenas, hemos realizado la issue, ya lo podéis verificar.

**Comment by scalafat-dgtic** [comment]
- Hi ha un error en cercar per data (o això o falta indicar si ha d'haver algun camp obligatori). També falla si fas cerca per data amb el num.Registre correcte

![image](https://user-images.githubusercontent.com/44995350/212062592-263af634-291f-4e79-8715-11fa392f24e8.png)

![image](https://user-images.githubusercontent.com/44995350/212063569-0db89695-5bbd-425d-9053-b3299f8844c5.png)

- Falta de format en el núm de Butlletí? (2023/005) 

![image](https://user-images.githubusercontent.com/44995350/212063341-3e13e402-7ad6-4eaa-a4f2-3104ecab9885.png)

- Revisar literal: **Traspàs** del BOIB

**Comment by episano-dgtic** [comment]
De cara creación normativa una vez elegida normativa a migrar.  No se incluyen los campos en castellano, ni se define por defecto, el boib como boletín.

**Comment by jcerdar-indra** [comment]
Respecto a los comentarios de esta issue, hemos ido contestando punto a punto los temas que se han resuelto en el tag [rolsac2-2.0-S7_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S7_2). Los puntos que no se han comentado, son temas que estamos pendientes de revisarlos o actualizarlos en una próxima subida.

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S8_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_2) se vuelve a poner el literal a "Núm. Registre"

**Comment by episano-dgtic** [comment]
Funciona correctamente, ambos idiomas. Hay aun problemas busqueda relacionados con eboib. Ya que actualmente en producción tb tenemos problemas migrar alguna norma último boib 039/2023. En nuestros entornos con boib anteriores va bien, aunque en vuestro entorno no funciona
