### ISSUE TITLE
S6-4 FINALITZAR ASSIGNACIONS DE NORMATIVES I LES SEVES DEPENDÈNCIES

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#44]
Es crearan les assignacions de normatives que falten

**Comment by slromero-indra** [comment]
Buenas, hemos realizado la issue, ya lo podéis verificar.

**Comment by jcerdar-indra** [comment]
Respecto a la siguiente issue, ¿hay algún punto que tendríamos que revisar o se podría cerrar?
