### ISSUE TITLE
S6-5 PANTALLA DE TRADUCCIÓ

### ISSUE THREAD

**Issue by bgarcia-dgtic** [GovernIB/rolsac2#45]
Es crearà una primera versió de la finestra de traduccions per permetre fer les traduccions de les diferents finestres.

**Comment by slromero-indra** [comment]
Incluido una primera versión, falta revisar un tema del botón de intercambiar idiomas y literales de tipo HTML.

**Comment by scalafat-dgtic** [comment]
Funciona bé.
- Si el camp és buit, que no retorni res. Ara retorna "XX ERROR XX"

![image](https://user-images.githubusercontent.com/44995350/212065508-86520a78-0e64-4086-9053-da603716590e.png)

**Comment by episano-dgtic** [comment]
Asegurar que el orden campos y etiquetas sea igual que en la gestión. En el caso de los trámites (requisitos aparece antes nombre).
![tramite_orden](https://user-images.githubusercontent.com/17451683/212678579-7bf7537e-2208-45f6-9ebc-c22c70e39471.gif)

Consideramos que en la edición de campos gestión literales individuales también  debería estar integrado el traductor.
![gestio_literals](https://user-images.githubusercontent.com/17451683/212678779-2a9999d7-988d-461d-af68-176e095bd91e.gif)

Los botones relacionados traductor  no debería aparecer si no está el plugin traductor creado/configurado, ó si la entidad sólo está configurada para un idioma. 

Por otro lado, los botones traductor no debería estar habilitado si se ha accedido a la ficha desde la visualización (ojo) de diferentes módulos (uo, normativa, procedimiento, servicio..)

**Comment by jcerdar-indra** [comment]
Respecto a los comentarios de esta issue, hemos ido contestando punto a punto los temas que se han resuelto en el tag [rolsac2-2.0-S7_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S7_2). Los puntos que no se han comentado, son temas que estamos pendientes de revisarlos o actualizarlos en una próxima subida.

**Comment by scalafat-dgtic** [comment]
Colocar check de "Substituir valor de l'idioma destí" justo debajo de las opciones de "Idioma Origen/Destí" porque lleva a confusión (da la sensación que estás marcando Idioma Destí)

![image](https://user-images.githubusercontent.com/44995350/217819021-ee312b46-fa8e-4398-b0fb-f19677ac75dc.png)

**Comment by bgarcia-dgtic** [comment]
Quan es crea una **Normativa** nova (sense que es faci un traspàs del BOIB) i es vol fer la traducció, el camp "Títol de la normativa" no es tradueix. A més, el text del camp "Títol de la normativa" es trasllada al camp "Enllaç de la norma" substituint el text que hi hagi escrit prèviament.

**Comment by episano-dgtic** [comment]
Aparecen campos de LOPD en la traducción de Entidades(superadministrador, configuración entidades), y no el campo interesa traducir. 
![traducir_entidades](https://user-images.githubusercontent.com/17451683/218749289-6990759d-173e-4d75-83c7-76fd081f5be4.gif)

**Comment by slromero-indra** [comment]
El plugin de traducción está a nivel de entidades por lo que desde el perfil de superadministrador, no es posible utilizar el plugin.

Se va a proceder a quitar el botón de traducir en las ventanas de super administrador (además, sólo hay literales en la descripción de entidad y de algunos tipos).

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S8_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_2) se corrige el error de traducción en la pantalla de normativas. Faltaría centrar el check de 'Substituir valor del idioma destino'. En la próxima revisión lo actualizaremos.
