### ISSUE TITLE
S7-1 INCORPORAR PROCEDIMIENTOS COMUNES

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#46]
Incorporar la lógica interna para mantener los procedimientos comunes

Canviar la seva visualització des de les pantalles d'un check a un desplegable amb les opcions Comú/Específic

![image](https://user-images.githubusercontent.com/44995350/212682467-dbdea1fa-b191-486d-9ef1-8109b3c09073.png)

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S7_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S7_2) se añade una primera versión de la implementación de procedimientos comunes. Se está terminando de revisar el detalle cuando se actualiza la UA. De momento, sólo se comporta correctamente cuando se inicia la pantalla. En la próxima actualización de ROLSAC2 se añadirá la funcionalidad completa

**Comment by scalafat-dgtic** [comment]
Como se ha comentado en #29, el desplegable pasa muy desapercibido.
Colocar, por ejemplo, al lado de "Taxa" y que lleve una etiqueta <label> con valor, por ejemplo, "Tipus"

**Comment by episano-dgtic** [comment]
Recordaros que la gestión de procedimientos comunes no puede estar disponible para el perfil gestor(creación, modificación, ó eliminación. 
En la creación de los procedimimientos, no debe darles opción a crear comunes. DE modo que por defecto se creen específicos.

**Comment by slromero-indra** [comment]
El tag S7_4 incluye los cambios, cuando podáis lo validáis.
