### ISSUE TITLE
S7-2 MEJORAS Y CORRECCIONES SOBRE PROCEDIMIENTOS, SERVICIOS Y NORMATIVAS y UA.

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#47]
- Revisión de las mejoras indicadas en las tareas de github
- Validar si hay cambios antes de salir sin guardar de la ventana principal

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S7_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S7_2) se han realizado las correcciones oportunas y se han documentado en sus respectivas issues.

**Comment by scalafat-dgtic** [comment]
- El text del missatge d'avís que sigui més gran. Es veu molt petit.
- Els botons, a la part dreta

![image](https://user-images.githubusercontent.com/44995350/217822156-2fa6d63d-53e3-4583-860e-c0e3a8b360c9.png)

**Comment by episano-dgtic** [comment]
En servicios/procedimientos no funciona envio de mensajes, ni cambio flujo para publicar (para el perfil gestores)

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S8_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_2) se corrigen los cambios de aspecto de la pantalla que se muestra al cerrar sin haber guardado los cambios. También indicar que se ha añadido esta funcionalidad en todos los mantenimientos de la aplicación. 

Respecto al comentario: _En servicios/procedimientos no funciona envio de mensajes, ni cambio flujo para publicar (para el perfil gestores)_, revisar la issue #42
