### ISSUE TITLE
S7-3 CREAR UNA PRIMERA VERSIÓN DE LA ASIGNACIÓN TEMATICA EN PROCEDIMIENTOS, SERVICIOS y UA’s

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#48]
Crear el componente para la seleccione de temas e incluirlos en las diferentes pantallas

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S7_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S7_2) se añade la implementación de la asignación temática en UAs, procedimientos y servicios.

**Comment by scalafat-dgtic** [comment]
Revisar: El número de módulos de asignación temática es proporcional al número de temas raíz creados, lo que puede llevar a una pantalla de módulos muy grande. 

Podría haber solo un módulo de asignación temática con la delegación de la asignación de temas en un nuevo popup (un 2do nivel). En la pantalla principal, pues, solo se podrían ver las descripciones de los temas escogidos (no es necesario representar el árbol entero).

Hay que tener en cuenta que se calcula que tendremos 21 temas y 72 subtemas, por ahora.

Además, al seleccionar varios temas, me ha aparecido el siguiente error:

![image](https://user-images.githubusercontent.com/44995350/218085285-afc692d9-af02-4feb-8111-16081cdf32c8.png)

**Comment by episano-dgtic** [comment]
Para evitar hubiera dos módulos en el bloque procedimientos. He creado un nuevo tema raiz DGCOM, y he cambiado el padre temas raíz previos. Ahora aparecen dos módulos "fadrins", otro nuevo de DGCOM pero que no aparecen las relaciones previas de dichos temas/subtemas raices previos.

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S8_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_2) se modifica la pantalla de mantenimiento de temáticas para mostrar la descripción. También se añade un buscador para poder filtrar los temas correctamente en el árbol. 

En la asignación temática en UAs, procedimientos y servicios se modifican las diferentes pantallas para mostrar la descripción en vez del identificador de los temas. 

Quedaría pendiente revisar un error que se da al cambiar el padre de un tema y pasarlo de un segundo a un tercer nivel. En la próxima revisión de la aplicación lo añadiremos.

**Comment by jcerdar-indra** [comment]
En el tag En el tag [rolsac2-2.0-S9_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_1) se resuelven los puntos mencionados en el comentario anterior.
