### ISSUE TITLE
S7-4 AUDITORIA (PROCEDIMIENTOS Y UNIDADES ADMINISTRATIVAS)

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#49]
Crear el apartado de auditorías en las diferentes pantallas y actualizar la información al guardar

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S7_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S7_2) se añade la implementación de las auditorias de UAs, procedimientos y servicios.

**Comment by episano-dgtic** [comment]
No se define en las auditorias cuando se crea, sólo después 2n guardado.

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S8_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_2) se añade auditoría al crear un procedimiento o servicio. Nos quedaría pendiente añadir la funcionalidad en las unidades administrativas.

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S9_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_1) se añade auditoría al crear una unidad administrativa.
