### ISSUE TITLE
S7-7 PANTALLA DE TRADUCCION v2

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#52]
Actualización del módulo de traducción para incorporar la funcionalidad de traducción HTML y realizar mejoras y correcciones sobre la pantalla.

**Comment by episano-dgtic** [comment]
Asegurar que el orden campos y etiquetas sea igual que en la gestión. En el caso de los trámites (requisitos aparece antes nombre).
![tramite_orden](https://user-images.githubusercontent.com/17451683/212668904-fd20336f-bc38-4f2b-8466-68cf29292c0e.gif)

No haya campos no existen(procedimientos) Finalitat, requisitos, dos destinataris.
![eliminar_campos_procedimiento](https://user-images.githubusercontent.com/17451683/212669119-eb284b53-7a65-4f72-8def-598f609431b5.gif)

Si se hace uso del traductor global en un procedimiento nuevo con todos los textos en catalán. No actualiza la iconografía de rojo a verde/naranja y no se permite el guardado campos porque supuestamente no está castellano.

A modo mejora.. consideramos que en la edición de campos gestión literales individuales también  debería estar integrado el traductor. 
![gestio_literals](https://user-images.githubusercontent.com/17451683/212668728-5188d47e-8444-4282-9c83-28ff74648fec.gif)

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S7_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S7_2) se actualiza el modulo de traducción para incorporar el editor HTML en los casos que sea necesario y se han realizado las mejoras solicitadas en la issue #45

**Comment by scalafat-dgtic** [comment]
Revisar el que es comenta en el #45

**Comment by jcerdar-indra** [comment]
Comentario en la #45
