### ISSUE TITLE
SuperAdmin - Perfil SuperAdministrador no ha de tenir entitat associada

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#53]
El perfil del SuperAdministrador no ha d'estar associat a cap Entitat (per això tenim els Administradors d'Entitat). 

Per tant, no ha d'aparèixer ni l'arbre jeràrquic ni el desplegable de les entitats

![image](https://user-images.githubusercontent.com/44995350/218066009-03097f04-d5b0-4d3a-87a6-5b6f0e428780.png)

**Comment by slromero-indra** [comment]
Los cambios para resolver la issue están incluidas en el tag rolsac2-2.0-S7_3.
