### ISSUE TITLE
SuperAdmin - No s'associen els rols creats de l'entitat amb els rols dels usuaris

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#54]
Al Keycloak tenim creats els següents rols de ROLSAC2 (RS2_ADC, RS2_ADE, RS2_GES, RS2_INF, RS2_SUP) però veim que estan 'hardcodejats' i, per tant, no es tenen en compte els rols gestionables des del backoffice per entitat.

S'hauria de separar, per un costat, el rol del SuperAdmin, que es pot quedar amb el RS2_SUP i que s'assignarà via Sistemes, de la resta de rols, que seran els definits des del backoffice segons la captura següent.

![image](https://user-images.githubusercontent.com/44995350/218069970-27d0a40b-b29d-4ae3-8200-81232973f7c8.png)

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S8_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_2) se añade la funcionalidad relacionada con los roles y permisos, issue #64
