### ISSUE TITLE
AdmEntitat - No s'ha de veure l'arbre jeràrquic

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#55]
Des de la pantalla d'Administrador de l'Entitat no s'ha de veure l'arbre jeràrquic ni realitzar cap filtre al respecte. 

Aquesta pantalla ha de permetre gestionar l'Entitat de manera global i mostrar, per tant, tota la informació de la mateixa, incloent tota la informació que duguin associades les UAs. En aquelles pantalles on es requereixi mostrar informació que pugui estar relacionada amb les UAs, es mostrarà, en una columna, per exemple, a quina UA pertany.

![image](https://user-images.githubusercontent.com/44995350/218071596-dd03c7c7-660a-4424-b770-07098146b29b.png)

**Comment by slromero-indra** [comment]
Los cambios para resolver la issue están incluidas en el tag rolsac2-2.0-S7_3.

Revisando todas las pantallas, se ha realizado lo siguiente:
- No se ve el árbol jerárquico en el perfil de superadministrador.
- No se ve el árbol jerárquico en el perfil de administrador entidad menos en la pantalla de administración de UAs.
- De momento, en el perfil de gestor, informador y adm. contenido se ve el árbol jerárquico (si más adelante, se podría ver de quitar en la pantalla de Normativas.
