### ISSUE TITLE
SuperAdmin - Fer agregacions en el menú

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#56]
Realitzar agregacions en el menú de "Configuració de plataforma" per que quedi de la següent manera:
- **Normatives**
     Tipus afectació
     Butlletins
     Tipus normativa
- **Procediments/Serveis**
     Silenci administratiu
     Forma d'inici
     Fi de la via administrativa (canviar "Tipus Via" per "Fi de la via administrativa")
     Legitimació
(sense un agregador, quedarien les següents)
- Matèria SIA
- Sexe
- Públic objectiu SIA

![image](https://user-images.githubusercontent.com/44995350/218075826-161df972-0045-4d44-b343-9a9fd25a495a.png)

**Comment by slromero-indra** [comment]
El tag S7_4 incluye los cambios, cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
Nos parece extraño como queda, separado de los demás, las 3 últimas opciones.
¿Las podemos poner arriba?

![image](https://user-images.githubusercontent.com/44995350/228243178-e526b3b8-98ed-4f53-9007-cedb85e75f79.png)

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S9_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_1) se reorganiza el desplegable.
