### ISSUE TITLE
Error en la pèrdua de sessió

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#58]
En la última versión, si estoy, por ejemplo, en la pantalla de normativas y pierdo la sesión por inactividad, al avanzar me salta la pantalla de autenticación. Si me autentico correctamente, me devuelve un "Error de Seguretat" cuando tengo todos los permisos.

![image](https://user-images.githubusercontent.com/44995350/218088622-29dad94d-0e9c-4a5e-a957-992a5dd4b6a7.png)

**Comment by slromero-indra** [comment]
El tag S7_4 incluye los cambios para solucionarlo, cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
OK, por ahora no me aparece.
Aún así, como mejora, más que cuando caduque se reenvíe a la página de autenticación (un usuario puede pensar que tiene sesión activa, hacer cambios y que se le redirija al guardar) tal vez se podría añadir que le salte una ventana de "sesión expirada" como tenemos en CARPETA.

![image](https://user-images.githubusercontent.com/44995350/223107632-66e1cf3e-917b-428e-937a-7750615341be.png)


Cuando se le dé al OK, le redirigiría a la pantalla de autenticación
