### ISSUE TITLE
SuperAdmin - Error de validació en crear Entitats

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#59]
En voler crear una nova Entitat, si li don a Tancar (sense guardar), no me deixa sortir sense que empleni els camps obligatoris.

Aquesta validació s'ha de fer només en el cas de que pitgi "Desar"

![image](https://user-images.githubusercontent.com/44995350/218089015-ac9c70d6-72ba-4517-970b-e3b7be078b63.png)

**Comment by slromero-indra** [comment]
No está incluido en los comentarios pero está solucionado en el tag rolsac2-2.0-S7_3, cuando podáis lo validáis.
