### ISSUE TITLE
Error en la visualització de .xhtml

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#60]
Després d'una pèrdua de sessió #58, en tornar a accedir a  https://dev.caib.es/rolsac2back i moure'm fins els procediments de l'Administrador de Continguts (https://dev.caib.es/rolsac2back/maestras/viewProcedimientos.xhtml ), m'apareix, de tant en tant, aquest error enlloc de mostrar-me la pantalla de Procediments

![image](https://user-images.githubusercontent.com/44995350/218105910-e253a303-55e8-4494-af73-8de5eddc6975.png)

Si torn a entrar a la URL en qüestió (https://dev.caib.es/rolsac2back/maestras/viewProcedimientos.xhtml ) se me veu correctament.

**Comment by slromero-indra** [comment]
Se añadió un control de perdida de sesión, mostrando un popup cuando se va a terminar: 

![imagen](https://github.com/GovernIB/rolsac2/assets/17451407/84bc32cb-9fb8-4e22-9fb0-a9d94ecb9c23)
