### ISSUE TITLE
SuperAdm - No es poden esborrar entitats

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#61]
Hem creat una entitat de prova i, a l'hora d'esborrar-la, ens diu que s'esborrin primer les unitats administratives relacionades quan aquesta entitat no en té.

![image](https://user-images.githubusercontent.com/44995350/218451518-4fc1e931-0960-4f0b-9706-ba4f9089afdc.png)

**Comment by slromero-indra** [comment]
Se incluirá en la primera versión del S8 ya que está asociada a la implementación de permisos.

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S10_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S10_2) se añade la siguiente funcionalidad.

**Comment by scalafat-dgtic** [comment]
He creat una entitat, i d'immediat l'he volguda esborrar.

M'ha botat una primera pantalla amb un error
![image](https://github.com/GovernIB/rolsac2/assets/44995350/8d63495c-d709-492a-b430-0327d7fe51f8)

Mirant els logs veig el següent:

"Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-02292: restricción de integridad (ROLSAC2.RS2_IDSOLR_ENTIDAD_FK) violada - registro secundario encontrado

Caused by: Error : 2292, Position : 0, Sql = delete from RS2_ENTIDA where ENTI_CODIGO=:1 , OriginalSql = delete from RS2_ENTIDA where ENTI_CODIGO=?, Error Msg = ORA-02292: restricción de integridad (ROLSAC2.RS2_IDSOLR_ENTIDAD_FK) violada - registro secundario encontrado"

Ara bé, tornant a prémer sobre 'esborrar', s'ha eliminat correctament.

**Comment by slromero-indra** [comment]
En el tag [rolsac2-2.0-S10_3](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S10_3) se ha incluido los cambios para solucionar el problema al borrar la entidad, cuando podáis, lo desplegáis para poder validarlo.

**Comment by scalafat-dgtic** [comment]
Faltaría cambiar el idioma del título del popup pero ya no sale el error
