### ISSUE TITLE
AdmEntitat - Canvis a Configuració d'Entitat

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#62]
- Moure els 4 camps de LOPD a una opció del menú de "Personalització Entitat"

![image](https://user-images.githubusercontent.com/44995350/218452587-fde9e57d-4c5e-4d0b-9766-bab78db1a78c.png)

![image](https://user-images.githubusercontent.com/44995350/218452667-24f14a9d-7ec9-430b-be13-577de32f91b3.png)

- Incorporar la possiblitat de pujar un fitxer CSS per canviar els estils per cada entitat.

**Comment by slromero-indra** [comment]
El tag S7_4 incluye los cambios, cuando podáis lo validáis.

**Comment by scalafat-dgtic** [comment]
No se actualizan los valores de la LOPD en un procedimiento ya creado (sí lo hace cuando son nuevos)

![image](https://user-images.githubusercontent.com/44995350/222711941-3bdc93a3-dcba-40bb-9c28-85c888a6903d.png)

![image](https://user-images.githubusercontent.com/44995350/222712023-e947975d-dd72-4c0b-81a8-99205a6d1349.png)

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S8_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_2) se añade la funcionalidad asociada a poder añadir un fichero CSS por entidad.

**Comment by slromero-indra** [comment]
Los datos que están en la LOPD de entidad, se utilizan cuando se crea el procedimiento/servicio, de tal manera que cada procedimiento puede tener unos datos distintos de lopd (si el usuario quiere cambiarlos), preferís de esta manera o queréis que sean fijos por el valor de la entidad?

**Comment by scalafat-dgtic** [comment]
Hola Sergio, al ponerlos en la pantalla de la entidad, entendemos que los valores LOPD van a ser fijos para todos.

**Comment by slromero-indra** [comment]
Los valores de lopd en procedimientos y servicios se extrae ya desde el valor de la entidad.
