### ISSUE TITLE
AdmEntitat - Camp TinyMCE dona problemes

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#63]
A la pantalla d'Unitats Administratives, en el camp Presentació, editable des de TinyMCE, dona problemes a l'hora de fer la transferència dels textos a la pantalla de traducció i el multi-idioma.

![image](https://user-images.githubusercontent.com/44995350/218740413-7179369d-dad2-4bf9-8065-6197cd1007d2.png)

![image](https://user-images.githubusercontent.com/44995350/218740470-a59cbdfb-738e-4280-91d1-f0e0cdb1c599.png)

Una vegada l'he traduït, si ho acceptam, segueix en blanc

![image](https://user-images.githubusercontent.com/44995350/218740606-e79a4723-4112-41a5-8cad-577ba21e204a.png)

![image](https://user-images.githubusercontent.com/44995350/218740687-81492016-baad-48d3-b460-2b4110b92ee9.png)

**Comment by slromero-indra** [comment]
El tag S7_4 no replica el error.

**Comment by scalafat-dgtic** [comment]
1. No se trasladan los estilos. (Solo he entrado editando la única UA que hay, he rellenado el texto, la he puesto en negrita i en "Heading 2") y he abierto el popup de traducción

![image](https://user-images.githubusercontent.com/44995350/222710064-b0dd48fc-f12d-468e-848b-986d4830dd27.png)

2. No acabo de replicar el error anterior pero el comportamiento es inestable. A veces se guardan los estilos en un idioma y a veces no... No sé si hay que plantearse quitarlo... (lo pensamos)

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S9_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_1) se resuelven los problemas mencionados en el comentario anterior.

**Comment by jcerdar-indra** [comment]
¿Se podría cerrar o hemos de revisar algún punto más?

**Comment by slromero-indra** [comment]
Podéis revisarlo? En principio están solventado los problemas.

**Comment by scalafat-dgtic** [comment]
Faltaría quitar los campos TinyMCE en Presentación y CV de los formularios y que se conviertan en campos de texto normales (o textareas) con posibilidad de traducción.

Dejamos para futuro una limpieza de los campos de la UA
