### ISSUE TITLE
S8-1 IMPLEMENTACION DE PERMISOS

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#64]
- Se cargarán los datos de autenticación de Keycloak
- Se realizarán las comprobaciones necesarias para que los usuarios solo tengan acceso a las páginas correspondientes a los roles que tenga asignados
- Para el usuario gestor solo se podrán acceder a las UAs que tengan asignadas
- Se permitirá el acceso a diferentes entidades

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S8_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S8_2) se añade la funcionalidad.

**Comment by jcerdar-indra** [comment]
Mediante la implementación de permisos, el acceso al backoffice de ROLSAC2 quedaría de la siguiente forma: 

En el script DML que se facilita (https://github.com/GovernIB/rolsac2/blob/rolsac-2.0/scripts/bbdd/oracle/02_sample_data.sql) al desplegar inicialmente la aplicación se crea un usuario (rolsac2) inicial. Este usuario se asocia a la entidad que se crea también en el DML. Este usuario rolsac2 tiene que tener los perfiles de RS2_SUP y RS2_ADE. 

Para acceder al backoffice mediante otros usuarios, las condiciones de acceso han de ser las siguientes: 

1. El usuario ha de estar dado de alta en ROLSAC2. Para dar de alta al usuario, un usuario Administrador de Entidad tiene que dar de alta el usuario correspondiente en el mantenimiento de usuarios. Al darlo de alta, ese usuario se asociará a la entidad correspondiente. 
2.  En Keycloak, asociar al usuario alguno de los 5 perfiles de aplicación que existen (RS2_SUP, RS2_ADE, RS2_ADC, RS2_INF, RS2_GES)
3.  Además de tener asociado el perfil de aplicación correspondiente, para poder acceder a la entidad a la que se asocia el usuario, será necesario que tenga asociado el rol de la entidad correspondiente que hace referencia al perfil de la aplicación. Por ejemplo, en caso de que un usuario tenga que acceder a la aplicación como administrador de contenidos, deberá tener el perfil de RS2_ADC y el rol de administrador de conteidos de la entidad en la que se da de alta.

**Comment by scalafat-dgtic** [comment]
El funcionamiento es correcto, pero se debe revisar #69
