### ISSUE TITLE
S8-2 PLUGIN INDEXACIÓN

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#65]
Se implementará el plugin de conexión con la librería SOLR-API para permitir la indexación de contenidos

**Comment by jcerdar-indra** [comment]
Para añadir el plugin se tienen que dar de alta las siguientes propiedades en el plugin: 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/96287364/223975318-5509cf2f-aa23-4711-92ee-88c3d997df10.png)

**Comment by scalafat-dgtic** [comment]
Vemos código añadido pero no vemos como probarlo.

**Comment by slromero-indra** [comment]
Buenas, se añadió una nueva opción en la monitorización asociado a la indexación (la opción que se llama reiniciar indices): 

![imagen](https://user-images.githubusercontent.com/17451407/224992651-6e6a5558-83a2-4f25-ad2e-09b558eb5247.png)

Funciona la indexación de pendientes y de procedimientos. En la ventana, se muestran los datos pendientes (incluirá más adelante las normativas y las UAs pendientes de indexar) y mostrará los procesos lanzados con un botón para ver el resumen de lo indexado.

Queréis que añadamos en la ventana de procedimientos y servicios, una pequeña sección (parecida a la de SIA) al final del todo que mostraría la información de indexación (la fecha en la que se mandó a indexar, cuando se indexó y el mensaje de indexado o error?)?

**Comment by jcerdar-indra** [comment]
Esta issue se relaciona con la issue https://github.com/GovernIB/rolsac2/issues/71, la cual se completa la entrega en este Sprint. ¿Podemos cerrar esta y los problemas que surjan documentarlos en la https://github.com/GovernIB/rolsac2/issues/71, la cual se entrega en el tag [rolsac2-2.0-S9_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_1)?

**Comment by scalafat-dgtic** [comment]
Cerramos pero hay errores que se muestran en #71
