### ISSUE TITLE
S8-3 PROCESO INDEXACIÓN

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#66]
Se creará el proceso de indexación de contenidos, permitiendo indexar contenidos a través de solr-API para procedimientos y servicios

**Comment by jcerdar-indra** [comment]
Esta issue se relaciona con la issue #71, la cual se completa la entrega en este Sprint. ¿Podemos cerrar esta y los problemas que surjan documentarlos en la #71, la cual se entrega en el tag [rolsac2-2.0-S9_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_1)?
