### ISSUE TITLE
S9-3 PLUGIN ORGANIGRAMA DIR3CAIB (VENTANA ORGANIGRAMA)

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#72]
- Creación de pantalla de consulta evolución del organigrama (comparativa entre árbol de unidades obtenido mediante el plugin de DIR3CAIB y el árbol de ROLSAC2) y lógica asociada.
- Creación de proceso automático para la obtención del árbol de DIR3CAIB

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S9_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_1) se crea la ventana de comparación del organigrama DIR3. 

Para poder probar la siguiente issue, comprobar que se ha creado el plugin de DIR3 en el mantenimiento de plugins: 
![image](https://user-images.githubusercontent.com/96287364/230134750-24e9c27b-400c-4724-b968-209488f247fc.png)

Una vez creado, dar de alta en los procesos automáticos el proceso DIR3 y, proceder al lanzado manual para obtener una primera versión del organigrama. 
![image](https://user-images.githubusercontent.com/96287364/230134815-d37850cc-a37d-4ecf-a754-3485218d0db6.png)

Una vez se ejecute correctamente, ya se puede acceder a la ventana del organigrama DIR3 para comparar el organigrama de ROLSAC2 con el de DIR3.

**Comment by scalafat-dgtic** [comment]
La sincronització funciona i podem veure l'organigrama. Hi ha alguna manera de poder fer una càrrega inicial?

![image](https://user-images.githubusercontent.com/44995350/232748357-8866061b-2b50-4355-819f-7baaef4851c2.png)

**Comment by jcerdar-indra** [comment]
Enviados los inserts de BBDD para la creación del organigrama por correo, el 25/04.

**Comment by scalafat-dgtic** [comment]
Inserts realizados. Se puede ver la comparativa.

![image](https://user-images.githubusercontent.com/44995350/234832609-d7fd1754-654a-44f7-9e03-405f7de45741.png)

Queda pendiente en próximos sprints habilitar los mecanismos para realizar la migración de información de UAs y procedimientos  de DIR3 a BD de ROLSAC2
