### ISSUE TITLE
S9-4 PLUGIN INTEGRACION SIA + TEST

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#73]
- Creación del plugin de integración con SIA, modelos necesarios y test unitario correspondiente.

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S9_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_1) se crea el plugin de SIA correspondiente.

**Comment by scalafat-dgtic** [comment]
Tenim manera de provar-ho?
