### ISSUE TITLE
S9-5 PROCESO INTEGRACION SIA (PRIMERA FASE) 

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#74]
- Lógica de negocio relacionada al proceso de integración con SIA
- Creación de clases base para la integración con SIA. 
- No se podrá probar en este Sprint esta primera fase del desarrollo

**Comment by jcerdar-indra** [comment]
En este Sprint se ha iniciado la siguiente tarea. Por ahora se puede observar en el menú de administrador de entidad la creación del mantenimiento de entidades raíz de SIA y la creación de la ventana de proceso de integración SIA. En el próximo Sprint se completará la tarea mediante la entrega de la segunda fase de esta tarea.

**Comment by scalafat-dgtic** [comment]
Queda pendiente de ver funcionamiento en #77
