### ISSUE TITLE
Error - No funciona plugin EBOIB

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#84]
Amb la pujada del darrer tag rolsac2-2.0-S9_1, no ens funciona el plugin del BOIB

Fent servir el test, se'ns retornen els edictes bé però amb aquest format. Pot ser sigui un problema de mostreig de dades?

`&lt;p&gt;&lt;span style="font-family:Times New Roman,Times,serif; font-size:12px"&gt;L'administració convocarà, amb caràcter mensual, una reunió per informar les patronals i els sindicats sobre les resolucions que es dictin d'acord amb aquestes instruccions.&lt;/span&gt;&lt;/p&gt;`
]]

**Comment by slromero-indra** [comment]
Subido en el tag rolsac2-2.0-S9_2

**Comment by scalafat-dgtic** [comment]
Ya funciona
