### ISSUE TITLE
AdmContinguts - Procediments - Revisar requisits de Tràmits a Procediments

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#86]
A l'hora de crear un tràmit nou dins un procediment, si es selecciona el canal Telemàtic i hem col·locat una URL, no s'hauria de demanar com obligatoris els camps Identificador i Versió ( i a l'inrevés).

Tal vegada es pot arreglar posant un desplegable, que també ho faria més intuitiu. També s'hauria de mostrar que el camp URL és obligatori en el cas de no marcar l'Identificador i la Versió.

![image](https://user-images.githubusercontent.com/44995350/235073834-c00f6184-3f74-4068-bb4e-3e04984bf7ec.png)

**Comment by episano-dgtic** [comment]
Por otro lado, si se marca el canal como telemático pero con datos de sistra específicos. 
![plataforma_sistra](https://user-images.githubusercontent.com/17451683/235089745-e43a52af-f3be-4986-9066-265cbf70ea30.gif)

La etiqueta "Plataforma de tramitació:" no está marcada como obligatoria, y no aparece en rojo.. y el mensaje de aviso indica"Si selecciona telemàtic i no selecciona una plantilla, ha d'emplenar la URL o la plantilla" cuando debería indicar: "Si selecciona telemàtic i no selecciona una plantilla, ha d'emplenar la URL o concretar tràmit específic sistra (identificador, versió i plataforma)"
![plataforma_sistra2](https://user-images.githubusercontent.com/17451683/235089765-13da56fa-6037-4a0e-aee5-acf198c8ba06.gif)

**Comment by slromero-indra** [comment]
Hemos creado un nuevo tag rolsac2-2.0-S9_4, incorpora:
 - Actualización del mensaje como se comenta.
 - Marca en rojo la plataforma de tramitación (si no está la url rellena)

Tenemos dos dudas:
- Respecto al primer comentario de un desplegable, queréis un desplegable al seleccionar telemático que te dejaría seleccionar dos opciones: "Seleccionar plantilla" o "introducir datos". Dependiendo de la opción, se muestra el desplegable de selección de plantilla o los otros 5 datos para introducirlos?
- En el mensaje de aviso  "Si selecciona telemàtic i no selecciona una plantilla, ha d'emplenar la URL o concretar tràmit específic **sistra** (identificador, versió i plataforma)", ¿cambiamos la palabra **sistra** por plataforma de tramitación?

**Comment by episano-dgtic** [comment]
Me parece genial la propuesta cambio, es más correcta plataforma de tramitación (era por simplificar)

**Comment by slromero-indra** [comment]
Los cambios han sido incluidos en el tag https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_5

**Comment by episano-dgtic** [comment]
Trans haber incluido el selector tipo canal telemático, no se ha modificado el mensajes de error para caso URL:

Si no se rellena URL: sale:Advertencia "Si selecciona telemàtic i no selecciona una plantilla, ha d'emplenar la URL o concretar tràmit específic sistra (identificador, versió i plataforma)" CAmbiarlo por:
Error "La url és obligatoria", y marcarse en campo en rojo. 

Por otro lado, si accedes directamente a un procedimiento para cambiar un canal telemático previo, a url.. si dejas la url en blanco te permite guardar sin advertencia o mensaje de error. 

En el campo url del canal telemático se trata como un campo opcional, es decir te permite guardar sólo en catalán ó castellano. Cuando en el rolsac2 se define idiomas obligatorios debería indicarse dicha url para todos idiomas definidos como obligatorios, aunque se replique. 


Y he detectado comportamiento extraños no consigo reproducir de forma clara.. ADjunto pantallazo: 
![giro aviso_selector](https://github.com/GovernIB/rolsac2/assets/17451683/4fd098ac-5cde-4d64-a441-a32e277234d0)

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S10_2](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S10_2) se solucionan los puntos comentados respecto al panel de canales de presentación, tanto en servicios como en procedimientos.
