### ISSUE TITLE
Pantalla Procediments

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac2#87]
1) Me deja publicar el procedimiento sin especificar ninguna asignación temática. Debe ser obligatorio, con los consiguientes mensajes al menos para publicar.

2) El campo apoderado debe ser un desplegable como Disponible para funcionario habilitado, obligatorio con misma opciones y mensajes  opción 'seleccione un', Si ó no. 
![apoderado](https://user-images.githubusercontent.com/17451683/235091827-90cd7c03-4ff1-4e12-a86a-6530ad802ebb.gif)

3) El caso de Disponible para funcionario habilitado, debe estar inhabilitado para gestores, al menos por el momento.

4) La opción Legitimació: es obligatoria, y por defecto debe indicarse la definida en el bloque Super administrador (Configuración plataforma->legitimació) para ello debe habilitarse un check en dicha pantalla.

5) Falta el botón enviar a sia no activo, en el caso que no esté definido.

**Comment by slromero-indra** [comment]
Hemos creado un nuevo tag rolsac2-2.0-S9_4, incorpora:
- Al seleccionar la opción de flujo, si no tienes tema, sale un mensaje de aviso.
- La selección de persona apoderada pasa de un checkbox a un desplegable obligatorio.
- Respecto a la opción, parece que nos salía ya inactiva para gestores, confirmarnos si era esa opción u otra.
- Se ha activado en la vista de tipos de legitimación, la opción de por defecto. En la vista de procedimientos, sólo cuando se crea (si queréis lo cambiamos también a cuando sea nulo) se setea la legitimación por el valor que esté marcado por defecto.
- El botón no está añadido ya que no está aun terminado el proceso SIA, cuando esté, se activará (además, tenemos que ver como reubicar los botones ya que empiezan a haber bastantes en la barra inferior.

**Comment by episano-dgtic** [comment]
En el pto 1. Se ha olvidado marcar el módulo como obligatorio, ASSIGNACIÓ TEMÀTICA - Tema pare, (incluir el * al final)

**Comment by slromero-indra** [comment]
Respecto de marcar con un * al final de una asignación temática, si hay 2 o más módulos con asignación temática, tienen que tener todos ellos un * de obligatoriedad o sólo uno de ellos?

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S11_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S11_1) se implementa lo comentado.
