### ISSUE TITLE
AdmEntidad - No es veuen Plantilles Presentació tràmits

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#88]
A BD, taula RS2_TRMPRE tenim informació sobre les plantilles de presentació de tràmits

![image](https://user-images.githubusercontent.com/44995350/235115169-7e122c8a-5a3f-408c-a18c-ebc31a8db989.png)

però no es mostren al llistat.

![image](https://user-images.githubusercontent.com/44995350/235115115-00d1961b-aff6-451f-ae03-6dd00c26ad26.png)

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S9_5](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S9_5) se soluciona este error.

**Comment by scalafat-dgtic** [comment]
Revisado
