### ISSUE TITLE
Pantalla SERVICIOS

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/rolsac2#89]
Si está desmarcado el check de informació LOPD no debe aparecer el módulo a la derecha (DOCUMENTS INFORMACIÓ LOPD), y si se pide publicarlo no debe solicitar se incluya
![LOPD_servicios](https://user-images.githubusercontent.com/17451683/235656029-e42607df-59cd-44e5-9cc2-e88d175f789a.gif)

Cambiar orden Canal presentación: Presencial, Telefonic, i telemàtic, incluyendo el desplegable especifica si es tipo plantilla, especifico, ó url según lo comentado en #ISSUE 87.

**Comment by slromero-indra** [comment]
Los cambios para no solicitar el documento lopd si está desmarcado el check de activo, está en el tag rolsac2-2.0-S9_5
