### ISSUE TITLE
S11-2 INICIO PROCESO DE MIGRACIÓN

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#93]
- Creación de scripts de automatización SQL para la migración de unidades administrativas.
- Creación de scripts de automatización SQL para la migración de las tablas maestras

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S11_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S11_1) se añade una ventana para la ejecución de tareas de migración, en el menú de Administrador de Entidad -> Monitorización de Entidad. Actualmente se ha implementado el proceso automático de migración de UAs. Para probarlo, es necesario ejecutar los GRANTS que se han enviado por correo. 

![image](https://github.com/GovernIB/rolsac2/assets/96287364/845fc92b-7239-431e-b687-481eaf5fe417)

**Comment by scalafat-dgtic** [comment]
Respecte a la migració d'informació, vàrem enviar una sèrie de correus però no hem tengut resposta.
Quedam a l'espera.

**Comment by scalafat-dgtic** [comment]
Cierro para seguir en las siguientes partes
