### ISSUE TITLE
S11-3 PLUGIN DE EMAIL + TEST

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#94]
- Creación del plugin para permitir el envío de correos electrónicos.
- Creación de test unitario para la prueba de envíos

**Comment by jcerdar-indra** [comment]
En el tag [rolsac2-2.0-S11_1](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S11_1) se crea el plugin de Email y se crea una pantalla de TEST para probarlo. 

En Administrador de Entidad -> Monitorización de Entidad -> Gestión Alertas y Avisos 

![image](https://github.com/GovernIB/rolsac2/assets/96287364/b7310650-3c0e-475b-9e22-c939cc723820)

**Comment by jcerdar-indra** [comment]
Para el correcto envío de emails, es necesario configurar en el standalone.xml del servidor web correspondiente lo siguiente: 

- En subsystem <subsystem xmlns="urn:jboss:domain:mail:3.0">, añadir una sesión de mail, con el JNDI indicado en el properties del plugin: 
![image](https://github.com/GovernIB/rolsac2/assets/96287364/fb8abdb2-f783-4650-a9b7-ff291f563fa0)

- Indicar en el tag <socket-binding-group /> el host y el puerto del servidor de mailing, asociado a la sesión de mail anterior: 
![image](https://github.com/GovernIB/rolsac2/assets/96287364/aabd5abd-1560-4399-89d6-774d3c1fa942)

**Comment by scalafat-dgtic** [comment]
Configurat i provat OK
Falta veure on incloem l'opció d'enviar l'email
