### ISSUE TITLE
S11-4 FINALIZACIÓN DEL CUADRO DE CONTROL

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#95]
- Revisión y análisis de los datos que se quieren mostrar en el cuadro de control.
- Adaptación de la lógica de negocio para la obtención de la información que mostrará el cuadro de control.
- Adaptación de la maqueta del cuadro a los datos reales

**Comment by scalafat-dgtic** [comment]
OK.

Estaria bé, per ara, col·locar el Quadre de Comandament com a ROLSAC1, que res més arribar a la pantalla de d'Administrador d'Entitat es mostri.

**Comment by scalafat-dgtic** [comment]
No hemos recibido noticias del último comentario. ¿Lo podéis mirar?

**Comment by slromero-indra** [comment]
Lo incorporaremos en la próxima subida de tag

**Comment by slromero-indra** [comment]
Generado el tag rolsac-2.0-S15_1 para que cuando entre como administrador de entidad, entre directamente al cuadro de control.
