### ISSUE TITLE
AdmEntidad - Indexación - No funciona ventana de log

### ISSUE THREAD

**Issue by scalafat-dgtic** [GovernIB/rolsac2#98]
El comportamiento de la ventana del log de cada proceso de indexación en solr/elastic es inestable. Muchas veces no se muestra aunque le des al botón.

¿Puede que se quede algún proceso pendiente de indexación que provoque lentitud al abrirlo?

**Comment by slromero-indra** [comment]
En el tag [rolsac2-2.0-S10_3](https://github.com/GovernIB/rolsac2/releases/tag/rolsac2-2.0-S10_3) se ha incluido mejoras (principalmente, por si se ha producido un error no esperado, poder ver que ha finalizado).

Hay que tener en cuenta que sólo puede haber un proceso ejecutándose cada vez. Una vez pulsado la acción, hay que darle al botón de refrescar ya que no se actualiza sólo ya que es una tarea totalmente asíncrona.
